import {shrinePhotos,photoCreditsUrl} from './gurdwara-photos';
import gurdwaras from './gurdwara-data.json';
export default function AtlasGuide(){return <>
 <h3>Map views, cities, rivers and Sikh heritage</h3>
 <p><b>Choose exact geography:</b> in Layers → Geographic view, choose a country, state/province, division, district or subdivision. Show only this isolates its source boundaries. Add to group combines territories across countries. Remove selection chips to refine the group, and use its detail buttons to show administrative levels. Source-era divisions are available where supplied; no missing divisions are invented.</p>
 <p><b>Nature:</b> rivers, mountains, plateaus and tree cover work over Political and other backgrounds, clipped to the selected source polygons. RiverATLAS v1 adds 232,370 source reaches across the atlas: regional density uses Strahler order 5+, and More tributaries uses order 3+. Its ~500 m model omits smaller streams and canals. Major river names come from Natural Earth. <a href="https://www.hydrosheds.org/hydroatlas" target="_blank" rel="noreferrer">Linke et al. (2019), RiverATLAS · CC BY 4.0</a>.</p>
 <p>Mountains and plateaus are approximate Natural Earth physical label areas, not elevation contours. Forests show a <a href="https://esa-worldcover.org/en/data-access" target="_blank" rel="noreferrer">2021 ESA WorldCover cartographic tree-cover overview</a> at ~1.3 km map pixels, not the analytical 10 m product; small woods can be absent and plantations included. © ESA WorldCover project 2021 / Contains modified Copernicus Sentinel data (2021) processed by ESA WorldCover consortium · CC BY 4.0. Colors, names and opacity are editable. SVG embeds the tree-cover raster and retains vector rivers/landforms. PNG/JPG include the same overlays.</p>
 <p><b>Tools:</b> Inspect (I) shows the source of the clicked area and offers fit, isolate or hide. Measure (M) adds approximate geodesic segment distances; it is not a road route or terrain survey. Clear measurement removes it. Rectangle, ellipse and polygon can color, clear colors or hide areas; they select area label points. Use the check button or Enter to finish a polygon and Escape to cancel.</p>
 <p>Use Map views & combinations for a strict individual region, custom region combination, full available map, Tricity or editable Historic Punjab context. Other regions’ colors are retained. Full map starts with outlines; Include enabled detail layers follows saved district/subdivision preferences.</p>
 <p>Tricity uses Chandigarh, S A S Nagar (Mohali) district and Panchkula district, not an exact urban or planning boundary. <a href="https://sasnagar.punjabpolice.gov.in/about_sas_nagar.php" target="_blank" rel="noreferrer">SAS Nagar Police reference</a>. Custom Historic Punjab uses editable modern administrative areas, not a dated historical province or Sikh Empire boundary.</p>
 <p>Full Pakistan includes 36 exact source-district division unions: Punjab 9, Sindh 6, Balochistan 8, KP 7, Pakistan-administered AJK 3 and GB 3. All 159 non-Islamabad source districts are assigned; Islamabad has no invented division. Membership follows the <a href="https://www.pbs.gov.pk/wp-content/uploads/2020/07/List-of-Administrative-Districts-2023.pdf" target="_blank" rel="noreferrer">PBS list frozen 1 March 2023</a>, with documented source-edition reconciliations. West Karachi retains the source’s unsplit Keamari area. These are not guaranteed current 2026 division boundaries.</p>
 <p>447 Natural Earth settlement points and 155 generalized river records cover the expanded atlas; the default major-city filter qualifies 353 source capital/population points before geographic filtering. Population is archival, not a current census. Auto-color city markers or containing visible districts; district auto-color is undoable and does not represent municipal city limits. River names, color and width are configurable. Place points follow selected source polygons, and rivers are clipped to their union. <a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">Natural Earth · public domain</a>.</p>
 <p>The Sikh heritage collection has 100 named sites: five Takhts, 15 additional editorial featured shrines and 80 other historic/notable gurdwaras. It includes Harmandir Sahib (Golden Temple), Fatehgarh Sahib and Jyoti Sarup Sahib. This is a curated collection, not an objective worldwide ranking or complete register. Markers use photographs of the named sites where a verified, reusable image is available. A neutral photo-unavailable badge is used for other sites. Published pins are representative points or complex centers, not surveyed entrances. Nearby sites overlap at small scales; zoom in or use the shrine picker.</p>
 <p>Identities are referenced to <a href="https://sgpc.net/gurdwara-sahib-section-85" target="_blank" rel="noreferrer">SGPC</a>, DSGMC and official district/tourism sources. Coordinate evidence is retained per site in app/gurdwara-sources.json. Location database: <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors · ODbL 1.0</a> with <a href="https://www.wikidata.org/wiki/Wikidata:Licensing" target="_blank" rel="noreferrer">Wikidata CC0</a> contributions. Retain attribution and follow ODbL when redistributing the database. All new view/overlay settings persist into Save/Load and exports.</p>
 <h3>Gurdwara photograph credits</h3><p>{shrinePhotos.length} photographs are bundled locally from Wikimedia Commons. Map markers display a rounded crop; click a marker to see the photograph and credit. Each image retains its individual license. Exported SVGs embed the photos and their attribution metadata; image exports include a link to the <a href={photoCreditsUrl} target="_blank" rel="noreferrer">complete photograph credits</a>. Photo licenses are separate from the location database license.</p><ul>{shrinePhotos.map(photo=><li key={photo.id}><b>{gurdwaras.find(g=>g.id===photo.id)?.name}</b> — {photo.author}. <a href={photo.licenseUrl} target="_blank" rel="noreferrer">{photo.license}</a> · <a href={photo.sourceUrl} target="_blank" rel="noreferrer">Original photograph</a>. Displayed as a rounded crop in the map marker.</li>)}</ul>
 </>;}
