export default function AtlasGuide(){return <>
 <h3>Map views, cities, rivers and Sikh heritage</h3>
 <p>Use Map views & combinations for a strict individual region, custom region combination, full available map, Tricity or editable Historic Punjab context. Other regions’ colors are retained. Full map starts with outlines; Include enabled detail layers follows saved district/subdivision preferences.</p>
 <p>Tricity uses Chandigarh, S A S Nagar (Mohali) district and Panchkula district, not an exact urban or planning boundary. <a href="https://sasnagar.punjabpolice.gov.in/about_sas_nagar.php" target="_blank" rel="noreferrer">SAS Nagar Police reference</a>. Custom Historic Punjab uses editable modern administrative areas, not a dated historical province or Sikh Empire boundary.</p>
 <p>Full Pakistan includes 36 exact source-district division unions: Punjab 9, Sindh 6, Balochistan 8, KP 7, Pakistan-administered AJK 3 and GB 3. All 159 non-Islamabad source districts are assigned; Islamabad has no invented division. Membership follows the <a href="https://www.pbs.gov.pk/wp-content/uploads/2020/07/List-of-Administrative-Districts-2023.pdf" target="_blank" rel="noreferrer">PBS list frozen 1 March 2023</a>, with documented source-edition reconciliations. West Karachi retains the source’s unsplit Keamari area. These are not guaranteed current 2026 division boundaries.</p>
 <p>447 Natural Earth settlement points and 155 generalized river records cover the expanded atlas; the default major-city filter qualifies 353 source capital/population points before geographic filtering. Population is archival, not a current census. Auto-color city markers or containing visible districts; district auto-color is undoable and does not represent municipal city limits. River names, color and width are configurable. Place points follow selected source polygons, and rivers are clipped to their union. <a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">Natural Earth · public domain</a>.</p>
 <p>The Sikh heritage collection has 100 named sites: five Takhts, 15 additional editorial featured shrines and 80 other historic/notable gurdwaras. It includes Harmandir Sahib (Golden Temple), Fatehgarh Sahib and Jyoti Sarup Sahib. This is a curated collection, not an objective worldwide ranking or complete register. Symbols are original stylized building designs, not exact architectural replicas. Published pins are representative points or complex centers, not surveyed entrances. Nearby sites overlap at small scales; zoom in or use the shrine picker.</p>
 <p>Identities are referenced to <a href="https://sgpc.net/gurdwara-sahib-section-85" target="_blank" rel="noreferrer">SGPC</a>, DSGMC and official district/tourism sources. Coordinate evidence is retained per site in app/gurdwara-sources.json. Location database: <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors · ODbL 1.0</a> with <a href="https://www.wikidata.org/wiki/Wikidata:Licensing" target="_blank" rel="noreferrer">Wikidata CC0</a> contributions. Retain attribution and follow ODbL when redistributing the database. All new view/overlay settings persist into Save/Load and exports.</p>
 </>;}
