import {Shield,LocateFixed} from 'lucide-react';
import {areaById,type MapDoc} from './map-model';
import {scopeFocusBounds} from './scope-model';
import {caseStudy,caseStudyLoadPreset} from './case-study-model';

export default function CaseStudyControls({doc,onChange,onFit}:{doc:MapDoc;onChange:(patch:Partial<MapDoc>)=>void;onFit:(bounds:number[])=>void}){
 function load(){const patch=caseStudyLoadPreset(doc);onChange(patch);const b=scopeFocusBounds({...doc,...patch});if(b)onFit(b);}
 return <section className="case-study-controls"><h2><Shield size={17}/> History case studies</h2><label className="field">Case study<select aria-label="History case study" value={doc.caseStudyId} onChange={e=>e.target.value===caseStudy.id?load():onChange({caseStudyId:'none'})}><option value="none">Custom map · no case-study caption</option><option value={caseStudy.id}>{caseStudy.name}</option></select></label><p>{caseStudy.summary}</p><p className="case-study-qualification">{caseStudy.qualification}</p><button onClick={load}><LocateFixed size={14}/> Load Sikh military & heritage case study</button>{doc.caseStudyId===caseStudy.id&&<button onClick={()=>{const a=areaById.get('pk-lahore-study');if(a)onFit(a.bbox);}}><LocateFixed size={14}/> Focus Lahore selection</button>}<p className="muted">Opens with every available state and province. Use the floating View menu for Complete map or Selected map to focus the heritage core. The preset loads the reference colors and names. Use Areas → Rename or select an area and use the pencil on the vertical toolbar to craft your own labels.</p><details><summary>Included districts and tehsils</summary>{caseStudy.groups.map(g=><div className="case-study-area-group" key={g.id}><strong><i style={{background:g.color}}/>{g.label} · {g.areaIds.length} selections</strong><p>{g.areaIds.map(id=>areaById.get(id)?.name||id).join(', ')}</p></div>)}<p>Excluded: {caseStudy.exclusions.join('; ')}.</p></details><details><summary>Reference map & boundary editions</summary><p>{caseStudy.boundaryNote}</p><p>{caseStudy.notes}</p><a href={caseStudy.image} target="_blank" rel="noreferrer"><img src={caseStudy.image} alt={caseStudy.referenceTitle+' — supplied hypothetical case study'} loading="lazy"/></a><small>Supplied map reference. Lahore polygons: © OpenStreetMap contributors · ODbL 1.0. Other boundaries retain their atlas source credits.</small></details></section>;
}
export function CaseStudyCaption({doc}:{doc:MapDoc}){return doc.caseStudyId==='sikh-heritage-core'?<div className="case-study-map-caption" aria-label="History case study caption"><strong>Sikh military & heritage case study</strong><span>Hypothetical / alternate history · editable modern units</span></div>:null;}
