'use client';
/* oxlint-disable next/no-img-element -- Bundled licensed photos are shared with the static map and SVG exporter. */
import {useMemo,useState} from 'react';
import {Users,Landmark,LocateFixed} from 'lucide-react';
import {areaById,regionById,type MapDoc} from './map-model';
import {scopePreset,scopeFocusBounds} from './scope-model';
import {demographicModes,demographicTitles,allDemographicRecords,scopeDemographics,demographicValue,demographicAreas,recordAreaId,demographicById,activeDemographicLevel,demographicYearLabel,demographicLevelNames,religionMode,communityColors,religionColors,type DemographicMode} from './demographic-model';
import {ReligionProfile} from './religion-profile';
import {communityShrines,communityShrineAllowed,shrineImageUrl,type CommunityShrine} from './community-shrine-model';

type Props={doc:MapDoc;onChange:(patch:Partial<MapDoc>)=>void;onFit:(bounds:number[])=>void;selectedId?:string};
export default function DemographicControls({doc,onChange,onFit,selectedId}:Props){
 const [region,setRegion]=useState(''),[profileQuery,setProfileQuery]=useState(''),[query,setQuery]=useState(''),[photoFailed,setPhotoFailed]=useState<Record<string,boolean>>({});
 const scoped=scopeDemographics(doc),level=activeDemographicLevel(doc),selected=demographicById.get(region||selectedId||(scoped[0]?recordAreaId(scoped[0]):''));
 const profiles=allDemographicRecords.filter(r=>(r.level||'region')===level&&(!profileQuery||((areaById.get(recordAreaId(r))?.name||'')+' '+(regionById.get(r.regionId)?.name||'')).toLowerCase().includes(profileQuery.toLowerCase())));
 const options=[...new Map([...(selected?[selected]:[]),...(profileQuery?profiles:scoped.length?scoped:profiles).slice(0,100)].map(r=>[recordAreaId(r),r])).values()];
 function changeLevel(value:MapDoc['demographicLevel']){setRegion('');setProfileQuery('');onChange({demographicLevel:value});}
 function showProfile(){if(!selected)return;const a=areaById.get(recordAreaId(selected));if(!a)return;const patch=a.level==='region'?scopePreset(doc,'single',{scopeRegion:a.region}):scopePreset(doc,'selection',{scopeAreas:[a.id]});onChange({...patch,demographicLevel:a.level==='tehsil'?'tehsil':a.level==='district'?'district':'region'});onFit(a.bbox);}
 const sites=useMemo(()=>communityShrines.filter(site=>communityShrineAllowed(site,doc)&&(site.name+' '+site.city+' '+site.community+' '+site.country).toLowerCase().includes(query.toLowerCase())),[doc,query]);
 function showShrine(site:CommunityShrine){const patch=scopePreset(doc,'single',{scopeRegion:site.regionId});onChange({...patch,hidden:doc.hidden.filter(id=>{const a=areaById.get(id);return !a||a.region!==site.regionId;}),communityShrines:true});const b=scopeFocusBounds({...doc,...patch});if(b)onFit(b);}
 return <>
  <section className="demographic-controls"><h2><Users size={17}/> Demographic layers</h2>
   <label className="field">Display over map<select aria-label="Demographic map layer" value={doc.demographicMode} onChange={e=>onChange({demographicMode:e.target.value as DemographicMode,...(e.target.value!=="none"?{empireId:"none"}:{}),...(religionMode(e.target.value as DemographicMode)?{demographicOpacity:1}:{})})}>{demographicModes.map(mode=><option key={mode} value={mode}>{demographicTitles[mode]}</option>)}</select></label>
   {religionMode(doc.demographicMode)&&<><label className="field">Administrative level<select aria-label="Religion administrative level" value={doc.demographicLevel} onChange={e=>changeLevel(e.target.value as MapDoc['demographicLevel'])}>{Object.entries(demographicLevelNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>{doc.demographicMode==='religion-share'&&<label className="field">Religious community<select aria-label="Religion population share community" value={doc.demographicReligion} onChange={e=>onChange({demographicReligion:e.target.value})}>{Object.keys(religionColors).map(name=><option key={name}>{name}</option>)}</select></label>}<p className="muted">Use the floating color key beside the map to change community colors. Darker shades in population-share mode mean a higher percentage.</p></>}
   <label className="field">Overlay opacity · {Math.round(doc.demographicOpacity*100)}%<input aria-label="Demographic opacity" type="range" min={.2} max={1} step={.05} value={doc.demographicOpacity} onChange={e=>onChange({demographicOpacity:Number(e.target.value)})}/></label>
   <label><input type="checkbox" aria-label="Show demographic labels" checked={doc.demographicLabels} onChange={e=>onChange({demographicLabels:e.target.checked})}/> Show demographic labels</label>
   <div className="demographic-coverage"><strong>{demographicYearLabel(doc)} · {scoped.length} matching {level==='region'?'regions':level==='district'?'districts':'tehsils'} of {demographicAreas(doc).length} in this view</strong><p>Religion totals use matching official census units: India 2011 and available Pakistan Punjab 2023 records. Boundaries and reported categories differ between sources; unmatched areas remain unshaded. Missing data is not zero.</p><p>Largest-group mode can show a group below 50%. Population-share mode shows the chosen community’s actual percentage.</p></div>
   {doc.demographicMode!=='none'&&!scoped.some(r=>demographicValue(r,doc.demographicMode))&&<output className="coverage-warning">No matching {demographicTitles[doc.demographicMode].toLowerCase()} records in this selection. Search for a matching census area below.</output>}
   <label className="field">Find a census profile<input type="search" aria-label="Search census profiles" placeholder="District, tehsil or state…" value={profileQuery} onChange={e=>setProfileQuery(e.target.value)}/></label>
   <label className="field">Inspect a census profile<select aria-label="Census profile" value={selected?recordAreaId(selected):''} onChange={e=>setRegion(e.target.value)}><option value="">Choose a covered area…</option>{options.map(r=><option key={recordAreaId(r)} value={recordAreaId(r)}>{areaById.get(recordAreaId(r))?.name||r.regionId} · {regionById.get(r.regionId)?.name} · {r.level||'region'} · {r.year}</option>)}</select></label>
   {options.length>=100&&<p className="muted">Search to find another profile. Up to 100 results are shown.</p>}
   {selected&&<div className="census-profile"><ReligionProfile record={selected} palette={doc.religionPalette}/>{selected.languages?.length? <details><summary>Mother-tongue and other indicators</summary><dl>{(['population','literacy','urban','language'] as const).map(mode=>{const v=demographicValue(selected,mode);return v?<div key={mode}><dt>{demographicTitles[mode]}</dt><dd>{v.text}</dd></div>:null;})}</dl>{selected.languages.map(v=><div className="census-share" key={v.name}><span>{v.name}</span><span>{v.share.toFixed(2)}%</span></div>)}</details>:null}<button onClick={showProfile}><LocateFixed size={13}/> Show this census region</button></div>}
  </section>
  <section className="community-shrine-controls"><h2><Landmark size={17}/> Community shrines</h2>
   <label><input type="checkbox" aria-label="Show community shrines" checked={doc.communityShrines} onChange={e=>onChange({communityShrines:e.target.checked})}/> Show major shrines on map</label>
   <label className="field">Community<select aria-label="Shrine community" value={doc.shrineCommunity} onChange={e=>onChange({shrineCommunity:e.target.value})}><option value="all">All communities</option>{Object.keys(communityColors).map(c=><option key={c}>{c}</option>)}</select></label>
   <label><input type="checkbox" aria-label="Show community shrine labels" checked={doc.communityShrineLabels} onChange={e=>onChange({communityShrineLabels:e.target.checked})}/> Shrine labels</label>
   <label className="field">Find a shrine<input type="search" aria-label="Search community shrines" value={query} placeholder="Name, city or community…" onChange={e=>setQuery(e.target.value)}/></label>
   <p className="muted">Selected major sites across six communities. Pins follow your geographic selection. Photographs retain their authors and licenses.</p>
   <div className="community-shrine-list">{sites.map(site=><article key={site.id}><div className="community-shrine-photo">{shrineImageUrl(site)&&!photoFailed[site.id]?<img src={shrineImageUrl(site)} alt={site.name} loading="lazy" onError={()=>setPhotoFailed(current=>({...current,[site.id]:true}))}/>:<span>Photo unavailable</span>}</div><h3>{site.name}</h3><span className="community-badge" style={{color:communityColors[site.community]}}>{site.community} · {site.city}, {site.country}</span><p>{site.description}</p>{site.photo&&<a href={site.photo.sourceUrl} target="_blank" rel="noreferrer" className="shrine-photo-credit">Photo: {site.photo.author} · {site.photo.license}</a>}<div className="geography-actions"><button onClick={()=>showShrine(site)}><LocateFixed size={13}/> Show on map</button><a href={site.sourceUrl} target="_blank" rel="noreferrer">Site source</a></div></article>)}{!sites.length&&<p>No matching shrines.</p>}</div>
  </section>
 </>;
}
