'use client';
// SVG district paths require button roles; HTML buttons cannot represent geographic shapes.
/* oxlint-disable jsx-a11y/prefer-tag-over-role */
import {useState,useEffect,useRef} from 'react';
import {Map as MapIcon,Paintbrush,Eraser,Pipette,Hand,Square,Circle,Pentagon,Undo2,Redo2,Download,Upload,Save,Plus,Minus,Maximize,Info,Search,ChevronRight,Layers} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {Slider} from '@/components/ui/slider';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import districts from './map-data.json';
import './studio.css';
type Paint={color:string;pattern:string};
type Doc={fills:Record<string,Paint>;title:string;legendTitle:string;groups:Record<string,string>;bg:string;border:string;uncolored:string;names:boolean;borders:boolean;width:number;labelSize:number;legend:boolean;legendX:number;legendY:number};
const initial:Doc={fills:{},title:'Punjab',legendTitle:'Legend',groups:{},bg:'#ffffff',border:'#526477',uncolored:'#e7edf2',names:true,borders:true,width:1,labelSize:11,legend:true,legendX:720,legendY:560};
const palette=['#2764d8','#58a9df','#89cbd0','#2d9477','#86bf69','#e9c75b','#ed9951','#df635b','#c474a2','#8761b2','#495774','#a5b0bc'];
const toolList=[['paint','Color',Paintbrush],['erase','Erase',Eraser],['pick','Pick color',Pipette],['pan','Move',Hand],['rect','Rectangle',Square],['ellipse','Ellipse',Circle],['polygon','Polygon',Pentagon]] as const;
const key=(p:Paint)=>p.color+'|'+p.pattern;
function inPoly(p:number[],r:number[][]){let c=false;for(let i=0,j=r.length-1;i<r.length;j=i++){if((r[i][1]>p[1])!==(r[j][1]>p[1])&&p[0]<(r[j][0]-r[i][0])*(p[1]-r[i][1])/(r[j][1]-r[i][1])+r[i][0])c=!c}return c}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
function validate(v:unknown):Doc{const x=v as Doc;if(!x||typeof x!=='object'||!x.fills||typeof x.fills!=='object')throw Error('Invalid map file');const hex=(s:unknown)=>typeof s==='string'&&/^#[0-9a-f]{6}$/i.test(s);const fills:Record<string,Paint>={};for(const [id,p]of Object.entries(x.fills)){if(!districts.some(d=>d.id===id)||!p||!hex(p.color)||!['solid','stripes','dots','cross'].includes(p.pattern))throw Error('Invalid district color');fills[id]=p}const result={...initial,fills};for(const k of ['title','legendTitle'] as const)if(typeof x[k]==='string')result[k]=x[k].slice(0,100);for(const k of ['bg','border','uncolored'] as const)if(hex(x[k]))result[k]=x[k];for(const k of ['names','borders','legend'] as const)if(typeof x[k]==='boolean')result[k]=x[k];for(const [k,min,max]of [['width',0.2,4],['labelSize',8,20],['legendX',15,760],['legendY',40,760]] as const)if(Number.isFinite(x[k]))result[k]=Math.min(max,Math.max(min,x[k]));if(x.groups&&typeof x.groups==='object')result.groups=Object.fromEntries(Object.entries(x.groups).filter(([,v])=>typeof v==='string').map(([k,v])=>[k,v.slice(0,80)]));return result}
export default function Home(){
 const [doc,setDoc]=useState<Doc>(initial),[past,setPast]=useState<Doc[]>([]),[future,setFuture]=useState<Doc[]>([]);
 const [color,setColor]=useState(palette[0]),[pattern,setPattern]=useState('solid'),[tool,setTool]=useState('paint'),[search,setSearch]=useState(''),[hover,setHover]=useState(''),[help,setHelp]=useState(false),[status,setStatus]=useState('Ready to color'),[zoom,setZoom]=useState(1),[pan,setPan]=useState([0,0]),[shape,setShape]=useState<number[][]>([]),[ready,setReady]=useState(false),[format,setFormat]=useState('png'),[exportWidth,setExportWidth]=useState(2400);
 const svgRef=useRef<SVGSVGElement>(null),fileRef=useRef<HTMLInputElement>(null),drag=useRef<{kind:string;start:number[];origin:number[]}|null>(null),current=useRef(doc);useEffect(()=>{current.current=doc},[doc]);
 const groups=Array.from(new Map(Object.values(doc.fills).map(p=>[key(p),p])).entries());
 function commit(next:Doc){if(JSON.stringify(next)===JSON.stringify(current.current))return;const prev=current.current;setPast(p=>[...p.slice(-79),prev]);setFuture([]);current.current=next;setDoc(next)}
 function change(p:Partial<Doc>){commit({...current.current,...p})}
 function undo(){if(!past.length)return;setFuture(f=>[doc,...f]);setDoc(past[past.length-1]);setPast(p=>p.slice(0,-1));setStatus('Undone')}
 function redo(){if(!future.length)return;setPast(p=>[...p,doc]);setDoc(future[0]);setFuture(f=>f.slice(1));setStatus('Redone')}
 function paint(ids:string[],erase=false){const fills={...current.current.fills};ids.forEach(id=>{if(erase)delete fills[id];else fills[id]={color,pattern}});change({fills});setStatus(`${erase?'Cleared':'Colored'} ${ids.length} district${ids.length===1?'':'s'}`)}
 function act(id:string,erase=false){if(tool==='pick'){const p=doc.fills[id];setColor(p?.color||doc.uncolored);setPattern(p?.pattern||'solid');setTool('paint');return}if(tool==='paint'||tool==='erase'||erase)paint([id],erase||tool==='erase')}
 // Restore browser storage after hydration; it is unavailable during server rendering.
 // oxlint-disable-next-line react/react-compiler
 useEffect(()=>{try{const saved=localStorage.getItem('punjab-studio-v1');if(saved){setDoc(validate(JSON.parse(saved)));setStatus('Restored your map')}}catch{}setReady(true)},[]);
 // Report a storage failure so the user can save a file instead.
 // oxlint-disable-next-line react/react-compiler
 useEffect(()=>{if(ready)try{localStorage.setItem('punjab-studio-v1',JSON.stringify(doc))}catch{setStatus('Browser storage unavailable — use Save')}},[doc,ready]);
 function save(){download(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}),'punjab-map.json');setStatus('Map settings saved')}
 function point(e:{clientX:number;clientY:number},map=false){const svg=svgRef.current!;const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const t=p.matrixTransform(svg.getScreenCTM()!.inverse());return map?[(t.x-pan[0])/zoom,(t.y-pan[1])/zoom]:[t.x,t.y]}
 function finishPolygon(){if(shape.length>=3)paint(districts.filter(d=>inPoly(d.center,shape)).map(d=>d.id));setShape([])}
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,[contenteditable=true]'))return;if(e.ctrlKey||e.metaKey){if(['z','y','s'].includes(e.key.toLowerCase()))e.preventDefault();if(e.key.toLowerCase()==='z'){if(e.shiftKey)redo();else undo()}if(e.key.toLowerCase()==='y')redo();if(e.key.toLowerCase()==='s')save();return}const t:Record<string,string>={s:'paint',f:'pick',z:'pan',r:'rect',e:'ellipse',p:'polygon'};if(t[e.key]){setTool(t[e.key]);setShape([])}if(e.key==='b')change({borders:!doc.borders});if(e.key==='Escape'){setShape([]);setTool('paint')}if(e.key==='Enter'&&tool==='polygon')finishPolygon()};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)});
 function recolor(k:string,c:string){const fills={...doc.fills};Object.keys(fills).forEach(id=>{if(key(fills[id])===k)fills[id]={...fills[id],color:c}});const g=groups.find(([s])=>s===k);change({fills,groups:{...doc.groups,...(g?{[c+'|'+g[1].pattern]:doc.groups[k]||''}:{})}})}
 async function exportMap(){try{const node=svgRef.current!.cloneNode(true) as SVGSVGElement;node.querySelectorAll('[data-editor]').forEach(n=>n.remove());node.querySelector('#geography')?.setAttribute('transform','');node.querySelectorAll('.district').forEach(n=>{n.setAttribute('stroke',doc.borders?doc.border:'none');n.setAttribute('stroke-width',String(doc.width))});node.setAttribute('xmlns','http://www.w3.org/2000/svg');node.setAttribute('width',String(exportWidth));node.setAttribute('height',String(Math.round(exportWidth*820/1000)));const data=new XMLSerializer().serializeToString(node);if(format==='svg')download(new Blob([data],{type:'image/svg+xml'}),'punjab-map.svg');else{const url=URL.createObjectURL(new Blob([data],{type:'image/svg+xml'}));const image=new Image();await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(Error('Image export failed'));image.src=url});const canvas=document.createElement('canvas');canvas.width=exportWidth;canvas.height=Math.round(exportWidth*820/1000);canvas.getContext('2d')!.drawImage(image,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,format==='jpg'?'image/jpeg':'image/png',0.95));if(!blob)throw Error('Export failed');download(blob,`punjab-map.${format}`)}setStatus('Map downloaded')}catch{setStatus('Export failed. Try SVG or a smaller image size.')}}
 const paintFill=(p?:Paint)=>!p?doc.uncolored:p.pattern==='solid'?p.color:`url(#pattern-${p.color.slice(1)}-${p.pattern})`;
 return <main className="studio"><header className="topbar"><div className="brand"><span className="brand-mark"><MapIcon size={24}/></span><div>Punjab <strong>Map Studio</strong><small>INDIA · DISTRICT MAP EDITOR</small></div></div><div className="header-actions"><span className="saved"><i/> Auto-save on this device</span><button onClick={()=>setHelp(true)}><Info size={17}/> Guide & source</button><button onClick={()=>fileRef.current?.click()}><Upload size={17}/> Load</button><button onClick={save}><Save size={17}/> Save</button><button className="primary" onClick={exportMap}><Download size={17}/> Export map</button></div></header>
 <div className="workspace"><aside className="settings"><div className="panel-heading"><span className="eyebrow">YOUR WORKSPACE</span><h1>Make Punjab yours.</h1><p>Choose a color. Click a district.</p></div><Tabs defaultValue="style"><TabsList className="studio-tabs"><TabsTrigger value="style">Style</TabsTrigger><TabsTrigger value="districts">Districts <span className="count">23</span></TabsTrigger></TabsList><TabsContent value="style"><section><h2><span>01</span> Color districts</h2><span className="label">Selected color</span><div className="color-picker"><input aria-label="Selected color" type="color" value={color} onChange={e=>setColor(e.target.value)}/><strong>{color.toUpperCase()}</strong><span>Custom</span></div><div className="palette">{palette.map(c=><button key={c} aria-label={`Choose ${c}`} aria-pressed={color===c} style={{background:c}} className={color===c?'selected':''} onClick={()=>setColor(c)}/>)}</div><span className="label">Fill style</span><div className="segments">{['solid','stripes','dots','cross'].map(p=><button key={p} className={pattern===p?'active':''} onClick={()=>setPattern(p)}>{p}</button>)}</div><div className="tool-note">Hold <kbd>Ctrl</kbd> and move to color multiple districts. <kbd>Shift</kbd> + click to erase.</div></section>
 <section><h2><span>02</span> Map appearance</h2><label className="field">Map title<input value={doc.title} onChange={e=>change({title:e.target.value})} maxLength={100}/></label><div className="toggle-row"><label htmlFor="names">District names</label><Switch id="names" checked={doc.names} onCheckedChange={v=>change({names:v})}/></div><div className="toggle-row"><label htmlFor="borders">District borders</label><Switch id="borders" checked={doc.borders} onCheckedChange={v=>change({borders:v})}/></div><div className="color-row">{([['bg','Background'],['uncolored','Uncolored'],['border','Borders']] as const).map(([k,l])=><label key={k}><input type="color" value={doc[k]} onChange={e=>change({[k]:e.target.value})}/>{l}</label>)}</div><div className="range-label">Border width <span>{doc.width.toFixed(1)} px</span></div><Slider aria-label="Border width" min={0.2} max={4} step={0.2} value={[doc.width]} onValueChange={v=>change({width:Array.isArray(v)?v[0]:v})}/><div className="range-label">Label size <span>{doc.labelSize} px</span></div><Slider aria-label="Label size" min={8} max={20} step={1} value={[doc.labelSize]} onValueChange={v=>change({labelSize:Array.isArray(v)?v[0]:v})}/></section>
 <section><h2><span>03</span> Legend</h2><div className="toggle-row"><label htmlFor="legend">Show legend</label><Switch id="legend" checked={doc.legend} onCheckedChange={v=>change({legend:v})}/></div><label className="field">Legend title<input value={doc.legendTitle} maxLength={100} onChange={e=>change({legendTitle:e.target.value})}/></label>{groups.length?groups.map(([k,p],i)=><div className="legend-entry" key={k}><input aria-label={`Group ${i+1} color`} type="color" value={p.color} onChange={e=>recolor(k,e.target.value)}/><input aria-label={`Group ${i+1} label`} placeholder={`Group ${i+1}`} value={doc.groups[k]||''} maxLength={80} onChange={e=>change({groups:{...doc.groups,[k]:e.target.value}})}/><span>{Object.values(doc.fills).filter(p=>key(p)===k).length}</span></div>):<p className="muted">Color a district to add your first legend group.</p>}<p className="muted">Drag the legend on the map to reposition it.</p></section></TabsContent>
 <TabsContent value="districts"><section><div className="search"><Search size={16}/><input aria-label="Search districts" placeholder="Find a district…" value={search} onChange={e=>setSearch(e.target.value)}/></div><p className="muted">Use the current color or eraser on a district below.</p><div className="district-list">{districts.filter(d=>d.name.toLowerCase().includes(search.toLowerCase())).map(d=><button key={d.id} onClick={()=>act(d.id)} onMouseEnter={()=>setHover(d.name)} onMouseLeave={()=>setHover('')}><i style={{background:doc.fills[d.id]?.color||doc.uncolored}}/>{d.name}<ChevronRight size={14}/></button>)}</div></section></TabsContent></Tabs><div className="source-note"><Layers size={16}/><div>23 districts · includes Malerkotla<button onClick={()=>setHelp(true)}>Boundary source & accuracy</button></div></div></aside>
 <div className="canvas-column"><div className="canvas-bar"><div className="breadcrumb">India <ChevronRight size={14}/><strong>Punjab</strong><span>Districts</span></div><div className="history"><button title="Undo (Ctrl+Z)" aria-label="Undo" disabled={!past.length} onClick={undo}><Undo2 size={18}/></button><button title="Redo (Ctrl+Y)" aria-label="Redo" disabled={!future.length} onClick={redo}><Redo2 size={18}/></button><span/><button onClick={()=>{change({fills:{},groups:{}});setStatus('All colors cleared — Undo to restore')}}>Clear colors</button></div></div>
 <div className="map-area"><div className="map-toolbar">{toolList.map(([id,label,Icon])=><button key={id} title={label} aria-label={label} aria-pressed={tool===id} className={tool===id?'active':''} onClick={()=>{setTool(id);setShape([])}}><Icon size={19}/></button>)}</div><div className="paper"><svg ref={svgRef} viewBox="0 0 1000 820" aria-label="Interactive map of Punjab’s 23 districts" style={{background:doc.bg,touchAction:'none',cursor:tool==='pan'?'grab':tool==='pick'?'crosshair':'default'}} onContextMenu={e=>{e.preventDefault();if(tool==='polygon')finishPolygon()}} onWheel={e=>{if(tool==='pan')setZoom(z=>Math.min(5,Math.max(0.7,z*(e.deltaY>0?0.9:1.1))))}} onPointerDown={e=>{if(e.button!==0)return;const p=point(e);if(tool==='pan'){drag.current={kind:'pan',start:p,origin:pan};e.currentTarget.setPointerCapture(e.pointerId)}else if(tool==='rect'||tool==='ellipse'){const m=point(e,true);drag.current={kind:tool,start:m,origin:[]};setShape([m,m]);e.currentTarget.setPointerCapture(e.pointerId)}else if(tool==='polygon')setShape(s=>[...s,point(e,true)])}} onPointerMove={e=>{const d=drag.current;if(!d)return;if(d.kind==='pan'){const p=point(e);setPan([d.origin[0]+p[0]-d.start[0],d.origin[1]+p[1]-d.start[1]])}else if(d.kind==='legend'){const p=point(e);setDoc(v=>({...v,legendX:Math.max(15,Math.min(760,d.origin[0]+p[0]-d.start[0])),legendY:Math.max(70,Math.min(750-groups.length*25,d.origin[1]+p[1]-d.start[1]))}))}else setShape([d.start,point(e,true)])}} onPointerUp={e=>{const d=drag.current;if(d&&(d.kind==='rect'||d.kind==='ellipse')){const end=point(e,true),[x,y]=d.start,[xx,yy]=end;paint(districts.filter(f=>{const [px,py]=f.center;if(d.kind==='rect')return px>=Math.min(x,xx)&&px<=Math.max(x,xx)&&py>=Math.min(y,yy)&&py<=Math.max(y,yy);return ((px-(x+xx)/2)/((xx-x)/2))**2+((py-(y+yy)/2)/((yy-y)/2))**2<=1}).map(f=>f.id));setShape([])}drag.current=null}}>
 <defs>{groups.map(([k,p])=>p.pattern!=='solid'&&<pattern key={k} id={`pattern-${p.color.slice(1)}-${p.pattern}`} width="8" height="8" patternUnits="userSpaceOnUse"><rect width="8" height="8" fill={p.color}/>{p.pattern==='dots'?<circle cx="4" cy="4" r="1.3" fill="white" opacity=".7"/>:<path d={p.pattern==='cross'?'M0 4H8M4 0V8':'M-2 2L2 -2M0 8L8 0M6 10L10 6'} stroke="white" opacity=".6" strokeWidth="1.6"/>}</pattern>)}</defs>
 <rect width="1000" height="820" fill={doc.bg}/><text x="48" y="50" fontSize="27" fontWeight="650" fill="#142b44" fontFamily="Arial,sans-serif">{doc.title}</text><text x="48" y="73" fontSize="11" letterSpacing="2" fill="#66778a" fontFamily="Arial,sans-serif">INDIA · DISTRICT MAP</text><g transform="translate(922,45)" fill="#526477"><path d="M0 25L7 4L14 25L7 20Z"/><text x="7" y="-3" textAnchor="middle" fontSize="11" fontFamily="Arial">N</text></g>
 <g id="geography" transform={`translate(${pan.join(' ')}) scale(${zoom})`}>{districts.map(d=><path className="district" key={d.id} d={d.d} fill={paintFill(doc.fills[d.id])} stroke={hover===d.name?'#15396a':doc.borders?doc.border:'none'} strokeWidth={hover===d.name?2:doc.width} strokeLinejoin="round" fillRule="evenodd" tabIndex={0} role="button" aria-label={`${d.name}, ${doc.fills[d.id]?'colored':'uncolored'}`} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();act(d.id)}}} onPointerEnter={e=>{setHover(d.name);if(e.ctrlKey)paint([d.id],e.shiftKey)}} onPointerLeave={()=>setHover('')} onClick={e=>{if(tool==='paint'||tool==='erase'||tool==='pick')act(d.id,e.shiftKey)}} onContextMenu={e=>{if(tool!=='polygon'){e.preventDefault();e.stopPropagation();paint([d.id],true)}}}><title>{d.name}</title></path>)}{doc.names&&districts.map(d=><text key={d.id} x={d.center[0]} y={d.center[1]} textAnchor="middle" dominantBaseline="middle" fontSize={doc.labelSize} fontFamily="Arial,sans-serif" fontWeight="500" fill="#152d42" stroke="white" strokeWidth="2.5" paintOrder="stroke" strokeLinejoin="round" pointerEvents="none">{d.name==='Shahid Bhagat Singh Nagar'?'S.B.S. Nagar':d.name==='S A S Nagar'?'S.A.S. Nagar':d.name}</text>)}{shape.length>0&&<g data-editor="selection" fill="#2764d830" stroke="#2764d8" strokeWidth="1.5" strokeDasharray="5 3" pointerEvents="none">{tool==='polygon'?<polygon points={shape.map(p=>p.join(',')).join(' ')}/>:tool==='ellipse'?<ellipse cx={(shape[0][0]+shape[1][0])/2} cy={(shape[0][1]+shape[1][1])/2} rx={Math.abs(shape[1][0]-shape[0][0])/2} ry={Math.abs(shape[1][1]-shape[0][1])/2}/>:shape.length>1?<rect x={Math.min(shape[0][0],shape[1][0])} y={Math.min(shape[0][1],shape[1][1])} width={Math.abs(shape[0][0]-shape[1][0])} height={Math.abs(shape[0][1]-shape[1][1])}/>:null}</g>}</g>
 {doc.legend&&groups.length>0&&<g transform={`translate(${doc.legendX},${Math.min(doc.legendY,750-groups.length*25)})`} style={{cursor:'move'}} onPointerDown={e=>{e.stopPropagation();setPast(p=>[...p.slice(-79),doc]);setFuture([]);drag.current={kind:'legend',start:point(e),origin:[doc.legendX,Math.min(doc.legendY,750-groups.length*25)]};svgRef.current!.setPointerCapture(e.pointerId)}}><rect x="-15" y="-26" width="240" height={48+groups.length*25} rx="5" fill="white" fillOpacity=".92" stroke="#dbe3eb"/><text fontFamily="Arial,sans-serif" fontSize="14" fontWeight="bold" fill="#152d42">{doc.legendTitle.slice(0,30)}</text>{groups.map(([k,p],i)=><g key={k} transform={`translate(0,${24+i*25})`}><rect width="14" height="14" y="-11" rx="2" fill={paintFill(p)}/><text x="24" fontSize="12" fill="#263d54" fontFamily="Arial,sans-serif">{(doc.groups[k]||`Group ${i+1}`).slice(0,30)}</text></g>)}</g>}
 <text x="48" y="794" fontSize="10" fontFamily="Arial,sans-serif" fill="#65778b">Boundary data: Esri India · IAB2024 service · 23 districts</text></svg></div><div className="zoom-controls"><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(.7,z-.2))}><Minus size={17}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(5,z+.2))}><Plus size={17}/></button><button aria-label="Fit map" onClick={()=>{setZoom(1);setPan([0,0])}}><Maximize size={17}/></button></div></div>
 <footer className="statusbar"><span role="status"><i/>{hover||status}</span><span>{Object.keys(doc.fills).length} / 23 districts colored</span></footer><div className="export-panel"><div><strong>Ready to share your map?</strong><p>Export your colors, labels, and legend.</p></div><div className="export-options"><div className="segments">{['png','svg','jpg'].map(f=><button key={f} onClick={()=>setFormat(f)} className={format===f?'active':''}>{f.toUpperCase()}</button>)}</div><label>Width <input aria-label="Export width" type="number" min="500" max="6000" step="100" value={exportWidth} onChange={e=>setExportWidth(Math.min(6000,Math.max(500,Number(e.target.value)||500)))}/> px</label><button className="primary" onClick={exportMap}><Download size={17}/> Download</button><button onClick={()=>window.print()}>Print / PDF</button></div></div></div></div>
 <input ref={fileRef} type="file" accept=".json,application/json" hidden onChange={async e=>{const input=e.currentTarget,file=input.files?.[0];if(!file)return;try{if(file.size>1000000)throw Error('File too large');commit(validate(JSON.parse(await file.text())));setStatus('Map loaded')}catch{setStatus('Could not load: choose a valid Punjab Map Studio JSON file.')}input.value=''}}/>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="guide"><DialogTitle>Map guide & boundary source</DialogTitle><DialogDescription>Punjab, India · 23 districts</DialogDescription><h3>Make your map</h3><p>Choose a color and fill style, then click districts. Right-click or Shift-click to erase. Ctrl + move paints multiple districts; Ctrl + Shift + move erases. Pick color copies a district’s fill.</p><p>Rectangle, ellipse, and polygon tools select districts by their label point. Click polygon vertices, then press Enter or right-click to finish. Escape cancels. Use Move to pan and scroll to zoom.</p><p>Ctrl+Z: undo · Ctrl+Y: redo · Ctrl+S: save settings. Drag the legend to position it. Exports include the full map. Print / PDF uses your browser’s print dialog.</p><h3>Boundary accuracy</h3><p>Geometries downloaded from <a href="https://livingatlas.esri.in/server/rest/services/IAB2024/India_Administrative_Boundaries_2024/MapServer/2" target="_blank" rel="noreferrer">Esri India’s IAB2024 district boundary service</a> on 6 September 2026, filtered to Punjab. All 23 supplied district geometries, including Malerkotla, are retained without line simplification. Display coordinates are projected and rounded to 0.001 SVG units.</p><p>The service’s edition is 2024. These boundaries are not independently certified against the latest Survey of India records and are not guaranteed to match MapChart’s dataset exactly.</p><p>This independent editor follows MapChart’s coloring workflow. It does not include MapChart accounts, scripts, or every advanced option.</p><a href="/punjab.geojson" download>Download the source GeoJSON</a></DialogContent></Dialog>
 </main>
}


