import {Crown,LocateFixed} from 'lucide-react';
import type {MapDoc} from './map-model';
import {empires,empireById,empirePreset,empireBounds,empireCount} from './empire-model';

export default function EmpireControls({doc,onChange,onFit}:{doc:MapDoc;onChange:(patch:Partial<MapDoc>)=>void;onFit:(bounds:number[])=>void}){
 const selected=empireById.get(doc.empireId);
 function show(id:string,detail=doc.empireDetail){onChange(empirePreset(doc,id,detail));const b=empireBounds(id);if(b)onFit([b[0]-2,b[1]-2,b[2]+2,b[3]+2]);}
 return <section className="empire-controls"><h2><Crown size={17}/> Historical empires</h2><p>Explore a dated reference extent using the districts and subdivisions on today’s map.</p><label className="field">Empire<select aria-label="Historical empire" value={doc.empireId} onChange={e=>e.target.value==='none'?onChange({empireId:'none'}):show(e.target.value)}><option value="none">Off · your own map colors</option>{empires.map(e=><option key={e.id} value={e.id}>{e.name} · {e.yearLabel}</option>)}</select></label><label className="field">Modern administrative detail<select aria-label="Empire administrative detail" value={doc.empireDetail} onChange={e=>selected?show(selected.id,e.target.value as MapDoc['empireDetail']):onChange({empireDetail:e.target.value as MapDoc['empireDetail']})}><option value="district">Districts</option><option value="tehsil">Districts + tehsils / subdivisions</option></select></label>{selected&&<><label className="field empire-color">Empire color<input type="color" aria-label="Empire color" value={doc.empireColor} onChange={e=>onChange({empireColor:e.target.value})}/></label><div className="demographic-coverage"><strong>{selected.name} · {selected.yearLabel}</strong><p>{empireCount(doc,'district')} visible districts · {empireCount(doc,'tehsil')} visible subdivisions with their source label point inside the reference extent.</p><p>Border areas can straddle historical territory. Coloring is an approximate comparison using modern boundaries, not a statement that an entire district was uniformly ruled.</p><p>{selected.note}</p></div><button onClick={()=>show(selected.id)}><LocateFixed size={14}/> Show empire on full map</button><details className="empire-source"><summary>Reference & method</summary><p>{selected.method}</p><p>{selected.sourceTitle}</p>{selected.sourceUrls.map(url=><a className="data-source-link" key={url} href={url} target="_blank" rel="noreferrer">Reference source</a>)}<p className="muted">{selected.license}</p></details></>}<p className="muted">Your custom colors are retained. Turn the empire view off to see them again. Hide/Unhide still applies to individual areas.</p></section>;
}
export function EmpireLegend({doc}:{doc:MapDoc}){const e=empireById.get(doc.empireId);if(!e||!doc.legend)return null;return <details className="empire-map-legend" open aria-label="Empire legend"><summary><i style={{background:doc.empireColor}}/>{e.name}</summary><small>{e.yearLabel} · approximate</small><p>Modern units · source label point inside reference extent</p><small>{empireCount(doc,'district')} districts · {empireCount(doc,'tehsil')} subdivisions visible</small></details>;}
