import type {FeatureCollection,Geometry,Position} from 'geojson';
import {areas,areaById,bounds,visible,effectivePaint,paintKey,download,type MapDoc,type Area} from './map-model';
import type {MapAPI} from './map-view';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
export async function exportMap(doc:MapDoc,api:MapAPI,format:string,width:number,current:boolean){
 const height=Math.round(width*.82),groups=[...new Map(Object.values(doc.fills).map(p=>[paintKey(p),p])).entries()];
 const legend=(ctx:CanvasRenderingContext2D)=>{if(!doc.legend||!groups.length)return;const x=width*doc.legendX/100,y=Math.min(height*doc.legendY/100,height-(groups.length*24+55)*width/1000),scale=width/1000;ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.fillStyle='#ffffffed';ctx.fillRect(-12,-27,238,groups.length*24+55);ctx.fillStyle='#18324a';ctx.font='bold 15px Arial';ctx.fillText(doc.legendTitle,0,-4,210);ctx.font='13px Arial';groups.forEach(([k,p],i)=>{ctx.fillStyle=p.color;ctx.fillRect(0,12+i*24,14,14);ctx.fillStyle='#18324a';ctx.fillText(doc.groups[k]||'Group '+(i+1),23,24+i*24,195)});ctx.restore()};
 if(doc.basemap!=='political'&&format!=='svg'){
  const url=await api.snapshot(),img=new Image();await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=reject;img.src=url});const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d')!;ctx.fillStyle=doc.bg;ctx.fillRect(0,0,width,height);ctx.drawImage(img,0,0,width,height);ctx.fillStyle='#ffffffdf';ctx.fillRect(0,0,width,70*width/1000);ctx.fillStyle='#142b44';ctx.font=`bold ${26*width/1000}px Arial`;ctx.fillText(doc.title,25*width/1000,45*width/1000,width*.9);legend(ctx);ctx.fillStyle='#ffffffee';ctx.fillRect(0,height-28*width/1000,width,28*width/1000);ctx.fillStyle='#344d65';ctx.font=`${10*width/1000}px Arial`;ctx.fillText((doc.kashmirView==='combined'?'Combined J&K · Indian claimed extent · disputed territory | ':'')+'Sources: Esri, Vantor, Earthstar Geographics, HERE, OpenStreetMap contributors · Natural Earth · boundary providers',10*width/1000,height-10*width/1000,width-20);const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,format==='jpg'?'image/jpeg':'image/png',.95));if(!blob)throw Error('Export failed');download(blob,'punjab-regional-map.'+format);return;
 }
 const shown=areas.filter(a=>visible(a,doc)),b=current?api.bounds():bounds(shown.filter(a=>a.level==='region'));
 // Exclude off-screen polygons before constructing paths, not only with SVG clipping.
 const list=current?shown.filter(a=>a.bbox[0]<=b[2]&&a.bbox[2]>=b[0]&&a.bbox[1]<=b[3]&&a.bbox[3]>=b[1]):shown;
 const included=new Set(list.map(a=>a.id));
 if(b[0]>b[2])throw Error('Show at least one region before exporting');
 const merc=(lat:number)=>Math.log(Math.tan(Math.PI/4+lat*Math.PI/360));const my0=merc(b[1]),my1=merc(b[3]);const sc=Math.min(910/(b[2]-b[0]),680/(my1-my0)*Math.PI/180);
 const p=(pos:Position)=>[45+(pos[0]-b[0])*sc,90+(my1-merc(pos[1]))*180/Math.PI*sc];
 const path=(g:Geometry):string=>{if(g.type==='Polygon')return g.coordinates.map(r=>'M'+r.map(c=>p(c).map(v=>v.toFixed(2)).join(',')).join('L')+'Z').join('');if(g.type==='MultiPolygon')return g.coordinates.map(c=>path({type:'Polygon',coordinates:c})).join('');if(g.type==='LineString')return 'M'+g.coordinates.map(c=>p(c).map(v=>v.toFixed(2)).join(',')).join('L');if(g.type==='MultiLineString')return g.coordinates.map(c=>path({type:'LineString',coordinates:c})).join('');return ''};
 const keys=[...new Set(list.map(a=>a.region+'-'+a.level))],cache=api.getData();const sources=await Promise.all(keys.map(async k=>({k,geo:cache[k]||await fetch('/data/'+k+'.geojson').then(r=>{if(!r.ok)throw Error('Layer not loaded');return r.json() as Promise<FeatureCollection>})})));
 const defs=groups.filter(([,p])=>p.pattern!=='solid').map(([k,p])=>`<pattern id="p${esc(k)}" width="8" height="8" patternUnits="userSpaceOnUse"><rect width="8" height="8" fill="${p.color}"/>${p.pattern==='dots'?'<circle cx="4" cy="4" r="1.3" fill="white" opacity=".65"/>':`<path d="${p.pattern==='cross'?'M0 4H8M4 0V8':'M0 8L8 0M-2 2L2 -2M6 10L10 6'}" stroke="white" opacity=".6" stroke-width="1.5"/>`}</pattern>`).join('');
 const pieces:string[]=[];const borderPieces:string[]=[];const labels:Area[]=[];
 for(const level of ['region','district','tehsil','uc','division'])for(const {geo}of sources)for(const f of geo.features){const a=areaById.get(String(f.id));if(!a||a.level!==level||!included.has(a.id))continue;const fill=effectivePaint(a,doc);const color=a.level==='division'?'none':fill?(fill.pattern==='solid'?fill.color:`url(#p${esc(paintKey(fill))})`):doc.uncolored;const strokeOn=doc.borders&&(level==='region'||(level==='district'?doc.districtBorders:level==='tehsil'?doc.tehsilBorders:level==='division'?doc.divisionBorders:doc.detailBorders));pieces.push(`<path d="${path(f.geometry)}" fill="${color}" fill-rule="evenodd"/>`);if(strokeOn)borderPieces.push(`<path data-area="${esc(a.id)}" d="${path(f.geometry)}" fill="none" stroke="${doc.border}" stroke-width="${doc.width*(level==='region'||level==='division'?1.6:level==='tehsil'?.65:1)}"/>`);if(doc.names&&a.region!=='kashmir-united')labels.push(a)}
 pieces.push(...borderPieces);
 if(doc.rivers||doc.basemap==='rivers'){const rivers=await fetch('/data/rivers.geojson').then(r=>r.json() as Promise<FeatureCollection>);for(const f of rivers.features)pieces.push(`<path d="${path(f.geometry)}" fill="none" stroke="#148bd1" stroke-width="1.4"/>`)}
 const occupied:number[][]=[];
 if(doc.kashmirView==='combined'&&doc.names){const context=await fetch('/data/kashmir-context-labels.geojson').then(r=>{if(!r.ok)throw Error('Kashmir context labels not loaded');return r.json() as Promise<FeatureCollection>});for(const f of context.features){if(f.geometry.type!=='Point')continue;const [x,y]=p(f.geometry.coordinates);if(x<20||x>960||y<85||y>770)continue;const name=String(f.properties?.name||''),size=doc.labelSize+2,w=name.length*size*.5;occupied.push([x-w/2,y-size/2,x+w/2,y+size/2]);pieces.push(`<text x="${x}" y="${y}" font-size="${size}" text-anchor="middle" fill="#624821" stroke="white" stroke-width="2.8" paint-order="stroke">${esc(name)}</text>`)}}

 for(const a of labels.reverse()){const [x,y]=p(a.center);if(x<20||x>960||y<85||y>770)continue;const size=doc.labelSize,w=a.name.length*size*.5;const box=[x-w/2,y-size/2,x+w/2,y+size/2];if(occupied.some(r=>box[0]<r[2]+4&&box[2]>r[0]-4&&box[1]<r[3]+3&&box[3]>r[1]-3))continue;occupied.push(box);pieces.push(`<text x="${x}" y="${y}" font-size="${size}" text-anchor="middle" fill="#18324a" stroke="white" stroke-width="2.8" paint-order="stroke">${esc(a.name)}</text>`)}
 if(doc.cities){const cities=await fetch('/data/cities.geojson').then(r=>r.json() as Promise<FeatureCollection>);for(const f of cities.features){if(f.geometry.type!=='Point')continue;const [x,y]=p(f.geometry.coordinates);if(x<20||x>960||y<85||y>770)continue;pieces.push(`<circle cx="${x}" cy="${y}" r="3" fill="#18324a" stroke="white"/><text x="${x+5}" y="${y+4}" font-size="12" fill="#18324a" stroke="white" stroke-width="2.8" paint-order="stroke">${esc(f.properties?.name||'')}</text>`)}}
 const lg=doc.legend&&groups.length?`<g transform="translate(${doc.legendX*10},${Math.min(doc.legendY*8.2,760-groups.length*24)})"><rect x="-12" y="-27" width="238" height="${groups.length*24+55}" fill="#fffffff0"/><text font-size="15" font-weight="bold" fill="#18324a">${esc(doc.legendTitle.slice(0,30))}</text>${groups.map(([k,p],i)=>`<rect x="0" y="${12+i*24}" width="14" height="14" fill="${p.pattern==='solid'?p.color:`url(#p${esc(k)})`}"/><text x="23" y="${24+i*24}" font-size="13" fill="#18324a">${esc((doc.groups[k]||'Group '+(i+1)).slice(0,30))}</text>`).join('')}</g>`:'';
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 820" width="${width}" height="${height}" font-family="Arial,sans-serif"><defs>${defs}<clipPath id="extent"><rect x="15" y="80" width="970" height="700"/></clipPath></defs><rect width="1000" height="820" fill="${doc.bg}"/><text x="35" y="48" font-size="26" font-weight="bold" fill="#142b44">${esc(doc.title.slice(0,65))}</text><g clip-path="url(#extent)">${pieces.join('')}</g>${lg}${doc.kashmirView==='combined'?'<text x="35" y="790" font-size="10" fill="#624821">Combined Jammu &amp; Kashmir · Indian claimed extent · disputed territory, not present control</text>':''}<text x="35" y="803" font-size="10" fill="#526477">Esri India · LGD/Bharatlas · WFP/OCHA 2022 · Lahore/HDX detail · Natural Earth | Source dates and coverage differ</text></svg>`;
 const blob=new Blob([svg],{type:'image/svg+xml'});if(format==='svg'){download(blob,'punjab-regional-map.svg');return}const u=URL.createObjectURL(blob),img=new Image();await new Promise<void>((r,j)=>{img.onload=()=>r();img.onerror=j;img.src=u});const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;canvas.getContext('2d')!.drawImage(img,0,0,width,height);URL.revokeObjectURL(u);const png=await new Promise<Blob|null>(r=>canvas.toBlob(r,format==='jpg'?'image/jpeg':'image/png',.95));if(!png)throw Error('Export failed');download(png,'punjab-regional-map.'+format);
}
