'use client';
import {useEffect,useRef,useState} from 'react';
import type {Map as GLMap,FilterSpecification,ExpressionSpecification} from 'maplibre-gl';
import type {FeatureCollection} from 'geojson';
import {areas,areaById,areasByLayer,ucParents,allBounds,layerKeys,levels,visible,effectivePaint,type MapDoc} from './map-model';
import 'maplibre-gl/dist/maplibre-gl.css';
import mapWorkerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
export type MapAPI={fit:(b:number[])=>void;zoom:(n:number)=>void;bounds:()=>number[];getData:()=>Record<string,FeatureCollection>;snapshot:()=>Promise<string>;select:(shape:number[][],kind:string)=>string[]};
type Props={doc:MapDoc;tool:string;onPaint:(ids:string[],erase?:boolean)=>void;onPick:(id:string)=>void;onHover:(name:string)=>void;onStatus:(text:string)=>void;onReady:(api:MapAPI)=>void;onZoom:(zoom:number)=>void};
function inPoly(p:number[],r:number[][]){let c=false;for(let i=0,j=r.length-1;i<r.length;j=i++){if((r[i][1]>p[1])!==(r[j][1]>p[1])&&p[0]<(r[j][0]-r[i][0])*(p[1]-r[i][1])/(r[j][1]-r[i][1])+r[i][0])c=!c}return c}
export default function MapView(props:Props){
 const host=useRef<HTMLDivElement>(null),map=useRef<GLMap|null>(null),latest=useRef(props),data=useRef<Record<string,FeatureCollection>>({}),pending=useRef(new Set<string>()),hovered=useRef(''),poly=useRef<number[][]>([]),start=useRef<number[]|null>(null);
 const [loaded,setLoaded]=useState(false),[selection,setSelection]=useState<number[][]>([]),[error,setError]=useState('');
 useEffect(()=>{latest.current=props},[props]);
 function select(points:number[][],kind:string){const m=map.current;if(!m)return [];const d=latest.current.doc;return areas.filter(a=>a.level!=='region'&&a.level!=='division'&&visible(a,d)).filter(a=>{const p=m.project(a.center as [number,number]),r=d.regions[a.region];if(a.level==='district'&&r.tehsil)return false;if(a.level==='tehsil'&&r.uc&&ucParents.has(a.parent))return false;if(kind==='polygon')return inPoly([p.x,p.y],points);const [x,y]=points[0],[xx,yy]=points[1];if(kind==='ellipse')return ((p.x-(x+xx)/2)/((xx-x)/2))**2+((p.y-(y+yy)/2)/((yy-y)/2))**2<=1;return p.x>=Math.min(x,xx)&&p.x<=Math.max(x,xx)&&p.y>=Math.min(y,yy)&&p.y<=Math.max(y,yy)}).map(a=>a.id)}
 useEffect(()=>{let cancelled=false;let observer:ResizeObserver|undefined;
 // Bundle the worker explicitly: dependency optimization changes import.meta.url.
 import('maplibre-gl').then(gl=>{if(cancelled||!host.current)return;gl.setWorkerUrl(mapWorkerUrl);gl.setWorkerCount(2);const m=new gl.Map({container:host.current,style:{version:8,glyphs:location.origin+'/fonts/{fontstack}/{range}.pbf',sources:{},layers:[{id:'background',type:'background',paint:{'background-color':'#ffffff'}}]},center:[73.2,31.5],zoom:5,minZoom:3,maxZoom:17,renderWorldCopies:false,attributionControl:false,dragRotate:false,pitchWithRotate:false,canvasContextAttributes:{antialias:true,preserveDrawingBuffer:false},maxPitch:0});map.current=m;m.touchZoomRotate.disableRotation();m.boxZoom.disable();m.on('dataloading',()=>host.current?.setAttribute('aria-busy','true'));m.on('movestart',()=>host.current?.setAttribute('aria-busy','true'));m.on('idle',()=>host.current?.setAttribute('aria-busy','false'));m.on('error',e=>{latest.current.onStatus('Map resource: '+e.error.message.slice(0,100))});
 const fit=(b:number[])=>{if(b[0]>b[2]){latest.current.onStatus('Show a region first');return}m.fitBounds([[b[0],b[1]],[b[2],b[3]]],{padding:55,duration:650})};
 m.on('load',()=>{if(cancelled)return;for(const style of ['stripes','dots','cross']){const bytes=new Uint8Array(8*8*4);for(let y=0;y<8;y++)for(let x=0;x<8;x++){const show=style==='stripes'?(x+y)%8<2:style==='dots'?(x-4)**2+(y-4)**2<3:x===4||y===4;const i=(y*8+x)*4;bytes[i]=255;bytes[i+1]=255;bytes[i+2]=255;bytes[i+3]=show?160:0}m.addImage(style,{width:8,height:8,data:bytes})}for(const [id,service] of [['satellite','World_Imagery'],['physical','World_Topo_Map'],['streets','World_Street_Map']]){m.addSource('base-'+id,{type:'raster',tiles:['https://services.arcgisonline.com/ArcGIS/rest/services/'+service+'/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:19});m.addLayer({id:'base-'+id,type:'raster',source:'base-'+id,layout:{visibility:'none'}})}
 m.addSource('river-data',{type:'geojson',data:'/data/rivers.geojson'});m.addLayer({id:'river-lines',source:'river-data',type:'line',layout:{visibility:'none'},paint:{'line-color':'#148bd1','line-width':['interpolate',['linear'],['zoom'],4,1.3,10,3]}});m.addLayer({id:'river-names',source:'river-data',type:'symbol',layout:{visibility:'none','symbol-placement':'line','text-field':['get','name'],'text-font':['Noto Sans Regular'],'text-size':12},paint:{'text-color':'#0078b8','text-halo-color':'#ffffff','text-halo-width':1.3}});
 m.addSource('city-data',{type:'geojson',data:'/data/cities.geojson'});m.addLayer({id:'city-dots',source:'city-data',type:'circle',layout:{visibility:'none'},paint:{'circle-radius':3.5,'circle-color':'#192d49','circle-stroke-color':'#ffffff','circle-stroke-width':1.3}});m.addLayer({id:'city-names',source:'city-data',type:'symbol',layout:{visibility:'none','text-field':['get','name'],'text-font':['Noto Sans Regular'],'text-size':13,'text-offset':[0,1.1],'text-anchor':'top','text-allow-overlap':false,'symbol-sort-key':['*',-1,['get','population']]},paint:{'text-color':'#192d49','text-halo-color':'#ffffff','text-halo-width':1.8}});
 m.addSource('kashmir-context',{type:'geojson',data:'/data/kashmir-context-labels.geojson'});m.addLayer({id:'kashmir-context-names',source:'kashmir-context',type:'symbol',minzoom:3,layout:{visibility:'none','text-field':['get','name'],'text-font':['Noto Sans Regular'],'text-size':14,'text-max-width':13,'text-padding':5,'text-allow-overlap':false},paint:{'text-color':'#624821','text-halo-color':'#ffffff','text-halo-width':2}});
 fit(allBounds);setLoaded(true);latest.current.onReady({fit,zoom:n=>m.zoomTo(m.getZoom()+n,{duration:260}),bounds:()=>{const b=m.getBounds();return[b.getWest(),b.getSouth(),b.getEast(),b.getNorth()]},getData:()=>data.current,snapshot:()=>new Promise(resolve=>{m.once('render',()=>resolve(m.getCanvas().toDataURL('image/png')));m.triggerRepaint()}),select});latest.current.onStatus('Map ready · scroll to zoom, drag to move')});
 const hit=(p:{x:number;y:number})=>{const keys=Object.keys(data.current).filter(k=>m.getLayer(k+'-fill'));const f=m.queryRenderedFeatures([p.x,p.y],{layers:keys.map(k=>k+'-fill')}).find(f=>f.properties.level!=='region'&&f.properties.level!=='division');return f?.properties.id as string|undefined};
 m.on('click',e=>{const p=latest.current;if(['rect','ellipse'].includes(p.tool))return;if(p.tool==='polygon'){poly.current.push([e.point.x,e.point.y]);setSelection([...poly.current]);return}const id=hit(e.point);if(!id||p.tool==='pan')return;if(p.tool==='pick')p.onPick(id);else p.onPaint([id],p.tool==='erase'||e.originalEvent.shiftKey)});
 m.on('mousemove',e=>{const id=hit(e.point);if(id!==hovered.current){hovered.current=id||'';latest.current.onHover(id?areaById.get(id)?.name||'':'');if(id&&e.originalEvent.ctrlKey)latest.current.onPaint([id],e.originalEvent.shiftKey)}if(start.current)setSelection([start.current,[e.point.x,e.point.y]])});
 m.on('mousedown',e=>{if(['rect','ellipse'].includes(latest.current.tool)){e.preventDefault();start.current=[e.point.x,e.point.y];setSelection([start.current,start.current])}});
 m.on('mouseup',e=>{if(start.current){latest.current.onPaint(select([start.current,[e.point.x,e.point.y]],latest.current.tool));start.current=null;setSelection([])}});
 m.on('contextmenu',e=>{e.preventDefault();if(latest.current.tool==='polygon'){if(poly.current.length>=3)latest.current.onPaint(select(poly.current,'polygon'));poly.current=[];setSelection([])}else{const id=hit(e.point);if(id)latest.current.onPaint([id],true)}});
 m.on('zoomend',()=>latest.current.onZoom(m.getZoom()));observer=new ResizeObserver(()=>m.resize());observer.observe(host.current);
 }).catch(()=>setError('The WebGL map could not start. Enable hardware acceleration in your browser and reload.'));
 const keys=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,select,[role=dialog]'))return;if(e.key==='Enter'&&latest.current.tool==='polygon'){if(poly.current.length>=3)latest.current.onPaint(select(poly.current,'polygon'));poly.current=[];setSelection([])}if(e.key==='Escape'){poly.current=[];start.current=null;setSelection([])}};window.addEventListener('keydown',keys);
 return()=>{cancelled=true;observer?.disconnect();map.current?.remove();map.current=null;window.removeEventListener('keydown',keys)};
 },[]);
 useEffect(()=>{if(!loaded||!map.current)return;const m=map.current;const shape=['rect','ellipse','polygon'].includes(props.tool);if(shape)m.dragPan.disable();else m.dragPan.enable();if(props.tool==='polygon')m.doubleClickZoom.disable();else m.doubleClickZoom.enable();m.getCanvas().style.cursor=props.tool==='pan'?'grab':shape||props.tool==='pick'?'crosshair':'pointer';poly.current=[];start.current=null;setSelection([])},[props.tool,loaded]);
 function apply(){const m=map.current;if(!m)return;const d=latest.current.doc;for(const id of ['satellite','physical','streets'])m.setLayoutProperty('base-'+id,'visibility',d.basemap===id||(d.basemap==='rivers'&&id==='physical')?'visible':'none');for(const id of ['city-dots','city-names'])m.setLayoutProperty(id,'visibility',d.cities?'visible':'none');for(const id of ['river-lines','river-names'])m.setLayoutProperty(id,'visibility',d.rivers||d.basemap==='rivers'?'visible':'none');m.setLayoutProperty('kashmir-context-names','visibility',d.kashmirView==='combined'&&d.names?'visible':'none');m.setLayoutProperty('kashmir-context-names','text-size',d.labelSize+2);m.setPaintProperty('background','background-color',d.bg);for(const k of Object.keys(data.current)){const layerAreas=areasByLayer.get(k)!;const sample=layerAreas[0];const show=visible(sample,{...d,hidden:[]});const list=layerAreas.filter(a=>visible(a,d));const ids=list.map(a=>a.id);const filter:FilterSpecification=['in',['get','id'],['literal',ids]];const line=sample.level==='region'||(sample.level==='district'?d.districtBorders:sample.level==='tehsil'?d.tehsilBorders:sample.level==='division'?d.divisionBorders:d.detailBorders);for(const suffix of ['fill','line','stripes','dots','cross','labels'])if(m.getLayer(k+'-'+suffix)){m.setLayoutProperty(k+'-'+suffix,'visibility',show&&(suffix!=='labels'||(d.names&&sample.region!=='kashmir-united'))?'visible':'none');m.setFilter(k+'-'+suffix,filter)}const painted=list.filter(a=>effectivePaint(a,d));const fillColor=['match',['get','id'],...list.flatMap(a=>[a.id,effectivePaint(a,d)?.color||d.uncolored]),d.uncolored] as unknown as ExpressionSpecification;m.setPaintProperty(k+'-fill','fill-color',fillColor);m.setPaintProperty(k+'-fill','fill-opacity',sample.level==='division'?0:d.basemap==='political'?1:sample.level==='region'?0:['case',['in',['get','id'],['literal',painted.map(a=>a.id)]],d.opacity,0]);m.setPaintProperty(k+'-line','line-opacity',d.borders&&line?1:0);m.setPaintProperty(k+'-line','line-color',d.border);m.setPaintProperty(k+'-line','line-width',sample.level==='region'?d.width*1.8:sample.level==='division'?d.width*2:sample.level==='tehsil'?d.width*.65:d.width);m.setLayoutProperty(k+'-labels','text-size',d.labelSize+(sample.level==='region'?2:sample.level==='uc'?-1:0));for(const pattern of ['stripes','dots','cross'])if(m.getLayer(k+'-'+pattern))m.setFilter(k+'-'+pattern,['in',['get','id'],['literal',list.filter(a=>effectivePaint(a,d)?.pattern===pattern).map(a=>a.id)]]);}
 // Keep borders and labels above all fills after asynchronous layer loads.
 for(const level of levels)for(const k of Object.keys(data.current).filter(k=>k.endsWith('-'+level))){m.moveLayer(k+'-line');m.moveLayer(k+'-labels')}if(m.getLayer('kashmir-united-region-line'))m.moveLayer('kashmir-united-region-line');for(const id of ['river-lines','river-names','city-dots','city-names','kashmir-context-names'])m.moveLayer(id);
 }
 useEffect(()=>{if(!loaded||!map.current)return;const m=map.current;const wanted=layerKeys.filter(k=>{const a=areasByLayer.get(k)![0];return visible(a,{...props.doc,hidden:[]})});for(const k of wanted){if(data.current[k]||pending.current.has(k))continue;pending.current.add(k);latest.current.onStatus('Loading boundary detail…');Promise.all([fetch('/data/'+k+'.geojson').then(r=>{if(!r.ok)throw Error(k);return r.json()}),fetch('/data/'+k+'-labels.geojson').then(r=>{if(!r.ok)throw Error(k+' labels');return r.json()})]).then(([geo,labels])=>{if(!map.current)return;const a=areasByLayer.get(k)![0];m.addSource(k,{type:'geojson',data:geo as FeatureCollection,tolerance:.2,maxzoom:15});m.addSource(k+'-points',{type:'geojson',data:labels as FeatureCollection});const outline=a.level==='division';m.addLayer({id:k+'-fill',source:k,type:'fill',paint:{'fill-color':['coalesce',['feature-state','color'],latest.current.doc.uncolored] as ExpressionSpecification,'fill-opacity':outline?0:1}});for(const style of ['stripes','dots','cross'])m.addLayer({id:k+'-'+style,source:k,type:'fill',filter:['in',['get','id'],['literal',[]]],paint:{'fill-pattern':style,'fill-opacity':outline?0:1}});m.addLayer({id:k+'-line',source:k,type:'line',paint:{'line-color':latest.current.doc.border,'line-width':1,...(a.level==='tehsil'?{'line-dasharray':[3,2]}:{})}});m.addLayer({id:k+'-labels',source:k+'-points',type:'symbol',minzoom:a.level==='uc'?10:a.level==='tehsil'?7.3:a.level==='district'?4.5:3,layout:{'text-field':['get','name'],'text-font':['Noto Sans Regular'],'text-size':12,'text-max-width':10,'text-padding':4,'text-allow-overlap':false},paint:{'text-color':'#1b354e','text-halo-color':'#ffffff','text-halo-width':1.5}});data.current[k]=geo as FeatureCollection;pending.current.delete(k);
 // Restore the hierarchy so tehsils and local detail receive clicks above districts.
 for(const level of ['region','district','tehsil','uc','division'])for(const key of Object.keys(data.current).filter(s=>s.endsWith('-'+level)))for(const suffix of ['fill','stripes','dots','cross'])m.moveLayer(key+'-'+suffix);apply();latest.current.onStatus('Boundary layer loaded')}).catch(()=>{pending.current.delete(k);latest.current.onStatus('Could not load '+k+'. Toggle the layer to retry.')})}apply();
 },[props.doc,loaded]);
 return <div className="gl-map"><div ref={host} className="gl-host"/>{error&&<div className="map-error">{error}</div>}{!loaded&&!error&&<div className="map-loading">Preparing map…</div>}{selection.length>0&&<svg className="selection-overlay"><g fill="#2764d82b" stroke="#2764d8" strokeDasharray="5 4" strokeWidth="2">{props.tool==='polygon'?<polygon points={selection.map(p=>p.join(',')).join(' ')}/>:selection.length>1&&props.tool==='ellipse'?<ellipse cx={(selection[0][0]+selection[1][0])/2} cy={(selection[0][1]+selection[1][1])/2} rx={Math.abs(selection[0][0]-selection[1][0])/2} ry={Math.abs(selection[0][1]-selection[1][1])/2}/>:selection.length>1?<rect x={Math.min(selection[0][0],selection[1][0])} y={Math.min(selection[0][1],selection[1][1])} width={Math.abs(selection[0][0]-selection[1][0])} height={Math.abs(selection[0][1]-selection[1][1])}/>:null}</g></svg>}</div>
}

