'use client';
import {useState} from 'react';
import {Layers,ChevronDown} from 'lucide-react';
import type {MapDoc} from './map-model';
import {detailModes,detailLabels,detailRegionIds,mapDetailValue,setMapDetail,type DetailMode,type DetailTarget} from './area-visibility-model';

export default function MapDetailControls({doc,target,onTarget,onChange,compact=false}:{doc:MapDoc;target:DetailTarget;compact?:boolean;onTarget:(target:DetailTarget)=>void;onChange:(patch:Partial<MapDoc>)=>void}){
 const [expanded,setExpanded]=useState({desktop:true,mobile:false}),size=compact?'mobile':'desktop';
 const ids=detailRegionIds(doc,target);
 const borders=[['regionBorders','State / country'],['districtBorders','District'],['tehsilBorders','Tehsil']] as const;
 return <details className="map-detail-controls" aria-label="Map detail and borders" open={expanded[size]} onToggle={e=>{const open=e.currentTarget.open;setExpanded(state=>state[size]===open?state:{...state,[size]:open});}}><summary><Layers size={16}/><span>Map detail</span><ChevronDown size={14}/></summary><div className="detail-fields"><label>Apply to<select aria-label="Apply map detail to" value={target} onChange={e=>onTarget(e.target.value as DetailTarget)}><option value="visible">Visible map</option><option value="all">All regions</option></select></label><label>Show<select aria-label="Show administrative detail" disabled={!ids.length} value={mapDetailValue(doc,target)} onChange={e=>onChange(setMapDetail(doc,e.target.value as DetailMode,target))}><option value="mixed" disabled>Custom / mixed</option>{detailModes.map(mode=><option key={mode} value={mode}>{detailLabels[mode]}</option>)}</select></label></div><p>{target==='visible'?'Changes only the areas in your current map.':'Also sets detail for regions you show later.'}</p><div className="detail-border-heading"><label><input type="checkbox" aria-label="Show map borders" checked={doc.borders} onChange={e=>onChange({borders:e.target.checked})}/> Borders</label><small>Whole map</small></div><div className="detail-border-buttons">{borders.map(([key,label])=><button type="button" key={key} aria-label={label+' borders'} aria-pressed={doc.borders&&doc[key]} disabled={!doc.borders} onClick={()=>onChange({[key]:!doc[key]})}>{label}</button>)}</div><details className="detail-more-borders"><summary>More border levels</summary><div className="detail-border-buttons">{([['provinceBorders','Province'],['divisionBorders','Division'],['detailBorders','Ward / UC']] as const).map(([key,label])=><button type="button" key={key} aria-label={label+' borders'} aria-pressed={doc.borders&&doc[key]} disabled={!doc.borders} onClick={()=>onChange({[key]:!doc[key]})}>{label}</button>)}</div></details></details>;
}
