'use client';
import {useEffect,useRef,useState} from 'react';
import type {Map as GLMap,FilterSpecification,ExpressionSpecification,GeoJSONSource} from 'maplibre-gl';
import type {FeatureCollection} from 'geojson';
import {areas,areaById,areasByLayer,ucParents,allBounds,layerKeys,levels,visible,effectivePaint,activeMetroLines,metroStationVisible,type MapDoc} from './map-model';
import 'maplibre-gl/dist/maplibre-gl.css';
import mapWorkerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
import {overlayMasks,scopedPoints,scopedRivers} from './spatial-overlays';
import {majorCity,cityPaintColor,shrineTierAllowed} from './overlay-model';
import {scopeGeometryKeys} from './scope-model';
import type {ShrineSymbolTier} from './gurdwara-icons';
import gurdwaras from './gurdwara-data.json';
import {shrinePhotoMarker,photoById} from './gurdwara-photos';
const emptyData:FeatureCollection={type:'FeatureCollection',features:[]};
export type MapAPI={fit:(b:number[])=>void;zoom:(n:number)=>void;bounds:()=>number[];getData:()=>Record<string,FeatureCollection>;snapshot:()=>Promise<string>;select:(shape:number[][],kind:string)=>string[]};
type Props={doc:MapDoc;tool:string;onPaint:(ids:string[],erase?:boolean)=>void;onPick:(id:string)=>void;onHover:(name:string)=>void;onStatus:(text:string)=>void;onReady:(api:MapAPI)=>void;onZoom:(zoom:number)=>void};
function inPoly(p:number[],r:number[][]){let c=false;for(let i=0,j=r.length-1;i<r.length;j=i++){if((r[i][1]>p[1])!==(r[j][1]>p[1])&&p[0]<(r[j][0]-r[i][0])*(p[1]-r[i][1])/(r[j][1]-r[i][1])+r[i][0])c=!c}return c}
export default function MapView(props:Props){
 const host=useRef<HTMLDivElement>(null),map=useRef<GLMap|null>(null),latest=useRef(props),data=useRef<Record<string,FeatureCollection>>({}),pending=useRef(new Set<string>()),hovered=useRef(''),poly=useRef<number[][]>([]),start=useRef<number[]|null>(null);
 const [loaded,setLoaded]=useState(false),[selection,setSelection]=useState<number[][]>([]),[error,setError]=useState('');
 const overlayCache=useRef<{key:string;cities?:FeatureCollection;rivers?:FeatureCollection;gurdwaras?:FeatureCollection}>({key:''}),spriteColor=useRef(''),spriteLoading=useRef(false);
 useEffect(()=>{latest.current=props},[props]);
 function select(points:number[][],kind:string){const m=map.current;if(!m)return [];const d=latest.current.doc;return areas.filter(a=>a.level!=='region'&&a.level!=='division'&&visible(a,d)).filter(a=>{const p=m.project(a.center as [number,number]),r=d.regions[a.region];if(a.level==='province'&&(r.district||r.tehsil))return false;if(a.level==='district'&&r.tehsil)return false;if(a.level==='tehsil'&&r.uc&&ucParents.has(a.parent))return false;if(kind==='polygon')return inPoly([p.x,p.y],points);const [x,y]=points[0],[xx,yy]=points[1];if(kind==='ellipse')return ((p.x-(x+xx)/2)/((xx-x)/2))**2+((p.y-(y+yy)/2)/((yy-y)/2))**2<=1;return p.x>=Math.min(x,xx)&&p.x<=Math.max(x,xx)&&p.y>=Math.min(y,yy)&&p.y<=Math.max(y,yy)}).map(a=>a.id)}
 useEffect(()=>{let cancelled=false;let observer:ResizeObserver|undefined;
 // Bundle the worker explicitly: dependency optimization changes import.meta.url.
 import('maplibre-gl').then(gl=>{if(cancelled||!host.current)return;gl.setWorkerUrl(mapWorkerUrl);gl.setWorkerCount(2);const m=new gl.Map({container:host.current,style:{version:8,glyphs:location.origin+'/fonts/{fontstack}/{range}.pbf',sources:{},layers:[{id:'background',type:'background',paint:{'background-color':'#ffffff'}}]},center:[73.2,31.5],zoom:5,minZoom:3,maxZoom:17,renderWorldCopies:false,attributionControl:false,dragRotate:false,pitchWithRotate:false,canvasContextAttributes:{antialias:true,preserveDrawingBuffer:false},maxPitch:0});map.current=m;m.touchZoomRotate.disableRotation();m.boxZoom.disable();m.on('dataloading',()=>host.current?.setAttribute('aria-busy','true'));m.on('movestart',()=>host.current?.setAttribute('aria-busy','true'));m.on('idle',()=>host.current?.setAttribute('aria-busy','false'));m.on('error',e=>{latest.current.onStatus('Map resource: '+e.error.message.slice(0,100))});
 const fit=(b:number[])=>{if(b[0]>b[2]){latest.current.onStatus('Show a region first');return}m.fitBounds([[b[0],b[1]],[b[2],b[3]]],{padding:55,duration:650})};
 m.on('load',()=>{if(cancelled)return;for(const style of ['stripes','dots','cross']){const bytes=new Uint8Array(8*8*4);for(let y=0;y<8;y++)for(let x=0;x<8;x++){const show=style==='stripes'?(x+y)%8<2:style==='dots'?(x-4)**2+(y-4)**2<3:x===4||y===4;const i=(y*8+x)*4;bytes[i]=255;bytes[i+1]=255;bytes[i+2]=255;bytes[i+3]=show?160:0}m.addImage(style,{width:8,height:8,data:bytes})}for(const [id,service] of [['satellite','World_Imagery'],['physical','World_Topo_Map'],['streets','World_Street_Map']]){m.addSource('base-'+id,{type:'raster',tiles:['https://services.arcgisonline.com/ArcGIS/rest/services/'+service+'/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:19});m.addLayer({id:'base-'+id,type:'raster',source:'base-'+id,layout:{visibility:'none'}})}
 m.addSource('river-data',{type:'geojson',data:emptyData});m.addLayer({id:'river-lines',source:'river-data',type:'line',layout:{visibility:'none'},paint:{'line-color':'#148bd1','line-width':['interpolate',['linear'],['zoom'],4,1.3,10,3]}});m.addLayer({id:'river-names',source:'river-data',type:'symbol',layout:{visibility:'none','symbol-placement':'line','text-field':['get','name'],'text-font':['Noto Sans Regular'],'text-size':12},paint:{'text-color':'#0078b8','text-halo-color':'#ffffff','text-halo-width':1.3}});
 m.addSource('city-data',{type:'geojson',data:emptyData});m.addLayer({id:'city-dots',source:'city-data',type:'circle',layout:{visibility:'none'},paint:{'circle-radius':5,'circle-color':['get','displayColor'],'circle-stroke-color':'#ffffff','circle-stroke-width':1.3}});m.addLayer({id:'city-names',source:'city-data',type:'symbol',layout:{visibility:'none','text-field':['get','name'],'text-font':['Noto Sans Regular'],'text-size':13,'text-offset':[0,1.1],'text-anchor':'top','text-allow-overlap':false,'symbol-sort-key':['*',-1,['get','population']]},paint:{'text-color':'#192d49','text-halo-color':'#ffffff','text-halo-width':1.8}});
 m.addSource('gurdwara-data',{type:'geojson',data:emptyData});m.addLayer({id:'gurdwara-symbols',source:'gurdwara-data',type:'symbol',layout:{visibility:'none','icon-image':['get','symbolId'],'icon-size':['get','symbolSize'],'icon-allow-overlap':true,'icon-ignore-placement':true,'text-field':['get','displayName'],'text-font':['Noto Sans Regular'],'text-size':11,'text-anchor':'top','text-offset':[0,1.8],'text-max-width':14,'symbol-sort-key':['get','priority']},paint:{'text-color':'#24435a','text-halo-color':'#ffffff','text-halo-width':2}});
 m.addSource('kashmir-context',{type:'geojson',data:'/data/kashmir-context-labels.geojson'});m.addLayer({id:'kashmir-context-names',source:'kashmir-context',type:'symbol',minzoom:3,layout:{visibility:'none','text-field':['get','name'],'text-font':['Noto Sans Regular'],'text-size':14,'text-max-width':13,'text-padding':5,'text-allow-overlap':false},paint:{'text-color':'#624821','text-halo-color':'#ffffff','text-halo-width':2}});
 fit(allBounds);setLoaded(true);latest.current.onReady({fit,zoom:n=>m.zoomTo(m.getZoom()+n,{duration:260}),bounds:()=>{const b=m.getBounds();return[b.getWest(),b.getSouth(),b.getEast(),b.getNorth()]},getData:()=>data.current,snapshot:()=>new Promise(resolve=>{m.once('render',()=>resolve(m.getCanvas().toDataURL('image/png')));m.triggerRepaint()}),select});latest.current.onStatus('Map ready · scroll to zoom, drag to move')});
 const hit=(p:{x:number;y:number})=>{const keys=Object.keys(data.current).filter(k=>m.getLayer(k+'-fill'));const f=m.queryRenderedFeatures([p.x,p.y],{layers:keys.map(k=>k+'-fill')}).find(f=>{const a=areaById.get(String(f.properties.id));return a&&a.level!=='region'&&a.level!=='division'&&visible(a,latest.current.doc)});return f?.properties.id as string|undefined};
 m.on('click',e=>{const p=latest.current;const shrine=m.getLayer('gurdwara-symbols')?m.queryRenderedFeatures(e.point,{layers:['gurdwara-symbols']})[0]:undefined;if(shrine&&['paint','pick','pan','erase'].includes(p.tool)){const node=document.createElement('div'),title=document.createElement('strong'),detail=document.createElement('p');title.textContent=String(shrine.properties.name);detail.textContent=String(shrine.properties.city)+' · '+(shrine.properties.tier==='takht'?'One of the five Takhts':shrine.properties.tier==='featured'?'Featured historic shrine':'Historic shrine');node.className='shrine-photo-popup';const photo=photoById.get(String(shrine.id||shrine.properties.id));if(photo){const image=document.createElement('img');image.src=photo.file;image.alt=String(shrine.properties.name);image.className='shrine-popup-image';node.appendChild(image);}node.appendChild(title);node.appendChild(detail);if(photo){const credit=document.createElement('a');credit.href=photo.sourceUrl;credit.target='_blank';credit.rel='noopener noreferrer';credit.className='shrine-photo-credit';credit.textContent='Photo: '+photo.author+' · '+photo.license;node.appendChild(credit);}else{const note=document.createElement('small');note.textContent='A verified photograph is not available for this site yet.';node.appendChild(note);}new gl.Popup({maxWidth:'300px'}).setLngLat(e.lngLat).setDOMContent(node).addTo(m);return;}if(['rect','ellipse'].includes(p.tool))return;if(p.tool==='polygon'){poly.current.push([e.point.x,e.point.y]);setSelection([...poly.current]);return}const id=hit(e.point);if(!id||p.tool==='pan')return;if(p.tool==='pick')p.onPick(id);else p.onPaint([id],p.tool==='erase'||e.originalEvent.shiftKey)});
 m.on('mousemove',e=>{const place=m.queryRenderedFeatures(e.point,{layers:['gurdwara-symbols','city-dots']})[0];if(place){latest.current.onHover(String(place.properties.name));hovered.current='';return;}const id=hit(e.point);if(id!==hovered.current){hovered.current=id||'';latest.current.onHover(id?areaById.get(id)?.name||'':'');if(id&&e.originalEvent.ctrlKey)latest.current.onPaint([id],e.originalEvent.shiftKey)}if(start.current)setSelection([start.current,[e.point.x,e.point.y]])});
 m.on('mousedown',e=>{if(['rect','ellipse'].includes(latest.current.tool)){e.preventDefault();start.current=[e.point.x,e.point.y];setSelection([start.current,start.current])}});
 m.on('mouseup',e=>{if(start.current){latest.current.onPaint(select([start.current,[e.point.x,e.point.y]],latest.current.tool));start.current=null;setSelection([])}});
 m.on('contextmenu',e=>{e.preventDefault();if(latest.current.tool==='polygon'){if(poly.current.length>=3)latest.current.onPaint(select(poly.current,'polygon'));poly.current=[];setSelection([])}else{const id=hit(e.point);if(id)latest.current.onPaint([id],true)}});
 m.on('zoomend',()=>latest.current.onZoom(m.getZoom()));observer=new ResizeObserver(()=>m.resize());observer.observe(host.current);
 }).catch(()=>setError('The WebGL map could not start. Enable hardware acceleration in your browser and reload.'));
 const keys=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,select,[role=dialog]'))return;if(e.key==='Enter'&&latest.current.tool==='polygon'){if(poly.current.length>=3)latest.current.onPaint(select(poly.current,'polygon'));poly.current=[];setSelection([])}if(e.key==='Escape'){poly.current=[];start.current=null;setSelection([])}};window.addEventListener('keydown',keys);
 return()=>{cancelled=true;observer?.disconnect();map.current?.remove();map.current=null;window.removeEventListener('keydown',keys)};
 },[]);
 useEffect(()=>{if(!loaded||!map.current)return;const m=map.current;const shape=['rect','ellipse','polygon'].includes(props.tool);if(shape)m.dragPan.disable();else m.dragPan.enable();if(props.tool==='polygon')m.doubleClickZoom.disable();else m.doubleClickZoom.enable();m.getCanvas().style.cursor=props.tool==='pan'?'grab':shape||props.tool==='pick'?'crosshair':'pointer';poly.current=[];start.current=null;setSelection([])},[props.tool,loaded]);
 function loadMetro(m:GLMap){
  if(data.current['delhi-metro-routes']||pending.current.has('delhi-metro'))return;
  pending.current.add('delhi-metro');latest.current.onStatus('Loading sourced metro tracks…');
  Promise.all(['routes','stations'].map(async kind=>{const response=await fetch('/data/delhi-metro-'+kind+'.geojson');if(!response.ok)throw Error('Metro '+kind+' unavailable');return response.json() as Promise<FeatureCollection>;})).then(([routes,stations])=>{
   if(map.current!==m)return;
   m.addSource('delhi-metro-routes',{type:'geojson',data:routes});m.addSource('delhi-metro-stations',{type:'geojson',data:stations});
   m.addLayer({id:'metro-halo',source:'delhi-metro-routes',type:'line',layout:{'line-cap':'round','line-join':'round'},paint:{'line-color':'#ffffff','line-width':['interpolate',['linear'],['zoom'],5,3,12,8]}});
   m.addLayer({id:'metro-lines',source:'delhi-metro-routes',type:'line',layout:{'line-cap':'round','line-join':'round'},paint:{'line-color':['get','color'],'line-width':['interpolate',['linear'],['zoom'],5,1.8,12,5]}});
   m.addLayer({id:'metro-stations',source:'delhi-metro-stations',type:'circle',minzoom:9,paint:{'circle-radius':['interpolate',['linear'],['zoom'],9,2.3,14,4],'circle-color':'#ffffff','circle-stroke-color':'#25384b','circle-stroke-width':1.4}});
   m.addLayer({id:'metro-station-names',source:'delhi-metro-stations',type:'symbol',minzoom:11,layout:{'text-field':['get','name'],'text-font':['Noto Sans Regular'],'text-size':11,'text-offset':[.6,.5],'text-anchor':'left','text-max-width':9,'text-padding':3},paint:{'text-color':'#25384b','text-halo-color':'#ffffff','text-halo-width':2}});
   data.current['delhi-metro-routes']=routes;data.current['delhi-metro-stations']=stations;pending.current.delete('delhi-metro');apply();latest.current.onStatus('Metro snapshot loaded · © OpenStreetMap contributors');
  }).catch(error=>{pending.current.delete('delhi-metro');latest.current.onStatus(String(error.message)+'. Toggle metro to retry.');});
 }
 function loadOverlay(m:GLMap,kind:'cities'|'rivers'|'gurdwaras'){
  const key='overlay-'+kind;if(data.current[key]||pending.current.has(key))return;pending.current.add(key);
  fetch('/data/'+kind+'.geojson').then(async r=>{if(!r.ok)throw Error(kind+' unavailable');return await r.json() as FeatureCollection;}).then(geo=>{if(map.current!==m)return;data.current[key]=geo;pending.current.delete(key);overlayCache.current.key='';apply();}).catch(error=>{pending.current.delete(key);latest.current.onStatus(String(error.message)+'. Toggle the overlay to retry.');});
 }
 function prepareShrineSymbols(m:GLMap,color:string){
  if(spriteColor.current===color||spriteLoading.current)return;
  spriteLoading.current=true;
  Promise.all(gurdwaras.map(async site=>{const svg=await shrinePhotoMarker(site.id,site.tier as ShrineSymbolTier,color);await new Promise<void>((resolve,reject)=>{const image=new Image();image.onload=()=>{if(map.current===m){const id='shrine-photo-'+site.id;if(m.hasImage(id))m.updateImage(id,image);else m.addImage(id,image);}resolve();};image.onerror=()=>reject(Error('Shrine photo marker unavailable'));image.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);});})).then(()=>{spriteColor.current=color;spriteLoading.current=false;if(map.current===m)apply();}).catch(error=>{spriteLoading.current=false;latest.current.onStatus(error.message);});
 }
 function applyOverlays(m:GLMap,d:MapDoc){
  const masks=overlayMasks(d,data.current),maskKey=masks.map(x=>x.id).sort().join('|');
  if(overlayCache.current.key!==maskKey){overlayCache.current={key:maskKey};}
  const cached=overlayCache.current;
  if(d.cities&&data.current['overlay-cities']&&!cached.cities)cached.cities=scopedPoints(data.current['overlay-cities'],masks);
  if((d.rivers||d.basemap==='rivers')&&data.current['overlay-rivers']&&!cached.rivers)cached.rivers=scopedRivers(data.current['overlay-rivers'],masks);
  if(d.gurdwaras&&data.current['overlay-gurdwaras']&&!cached.gurdwaras)cached.gurdwaras=scopedPoints(data.current['overlay-gurdwaras'],masks);
  const cityData:FeatureCollection={type:'FeatureCollection',features:(cached.cities?.features||[]).filter(f=>majorCity(f.properties||{},d)).map(f=>({...f,properties:{...f.properties,displayColor:cityPaintColor(f.properties||{},d)}}))};
  void (m.getSource('city-data') as GeoJSONSource).setData(cityData);
  m.setLayoutProperty('city-dots','visibility',d.cities?'visible':'none');m.setLayoutProperty('city-names','visibility',d.cities&&d.names?'visible':'none');m.setPaintProperty('city-names','text-color',['get','displayColor']);
  void (m.getSource('river-data') as GeoJSONSource).setData(cached.rivers||emptyData);
  const riverOn=d.rivers||d.basemap==='rivers';m.setLayoutProperty('river-lines','visibility',riverOn?'visible':'none');m.setLayoutProperty('river-names','visibility',riverOn&&d.riverLabels?'visible':'none');m.setPaintProperty('river-lines','line-color',d.riverColor);m.setPaintProperty('river-lines','line-width',d.riverWidth);m.setPaintProperty('river-names','text-color',d.riverColor);
  if(d.gurdwaras)prepareShrineSymbols(m,d.gurdwaraColor);
  const shrineData:FeatureCollection={type:'FeatureCollection',features:(cached.gurdwaras?.features||[]).filter(f=>shrineTierAllowed(f.properties?.tier,d)).map(f=>{const tier=f.properties?.tier as ShrineSymbolTier;return {...f,properties:{...f.properties,symbolId:'shrine-photo-'+String(f.id||f.properties?.id),symbolSize:(tier==='takht'?.95:tier==='featured'?.85:.7)*d.gurdwaraScale,displayName:d.gurdwaraLabels?f.properties?.name:'',priority:tier==='takht'?0:tier==='featured'?1:2}};})};
  void (m.getSource('gurdwara-data') as GeoJSONSource).setData(spriteColor.current===d.gurdwaraColor?shrineData:emptyData);m.setLayoutProperty('gurdwara-symbols','visibility',d.gurdwaras?'visible':'none');m.setLayoutProperty('gurdwara-symbols','text-offset',[0,2.5*d.gurdwaraScale+.5]);
 }
 function applyMetro(m:GLMap,d:MapDoc){
  if(!m.getLayer('metro-lines'))return;
  const scoped=d.mapScope!=='atlas'||d.delhiView==='ncr'||!!d.countryView,masks=overlayMasks(d,data.current);
  if(scoped){void (m.getSource('delhi-metro-routes') as GeoJSONSource).setData(scopedRivers(data.current['delhi-metro-routes'],masks));void (m.getSource('delhi-metro-stations') as GeoJSONSource).setData(scopedPoints(data.current['delhi-metro-stations'],masks));}
  else{void (m.getSource('delhi-metro-routes') as GeoJSONSource).setData(data.current['delhi-metro-routes']);void (m.getSource('delhi-metro-stations') as GeoJSONSource).setData(data.current['delhi-metro-stations']);}
  const lines=activeMetroLines(d),ids=lines.map(l=>l.id);
  const opacity=['case',['in',['get','id'],['literal',ids]],1,0] as ExpressionSpecification;
  const colors=(lines.length?['match',['get','id'],...lines.flatMap(l=>[l.id,d.metroLines[l.id].color]),'#808080']:'#808080') as ExpressionSpecification|string;
  for(const id of ['metro-halo','metro-lines']){m.setLayoutProperty(id,'visibility',d.delhiMetro?'visible':'none');m.setPaintProperty(id,'line-opacity',opacity);m.moveLayer(id);}
  m.setPaintProperty('metro-lines','line-color',colors);
  const stations=data.current['delhi-metro-stations'].features.filter(f=>metroStationVisible(f.properties?.lineIds||[],d));
  const stationIds=stations.map(f=>String(f.id)),stationOpacity=['case',['in',['get','id'],['literal',stationIds]],1,0] as ExpressionSpecification;
  m.setLayoutProperty('metro-stations','visibility',d.delhiMetro&&d.metroStations?'visible':'none');m.setPaintProperty('metro-stations','circle-opacity',stationOpacity);m.setPaintProperty('metro-stations','circle-stroke-opacity',stationOpacity);
  m.setLayoutProperty('metro-station-names','visibility',d.delhiMetro&&d.metroStations&&d.names?'visible':'none');m.setFilter('metro-station-names',['in',['get','id'],['literal',stationIds]]);m.moveLayer('metro-stations');m.moveLayer('metro-station-names');
 }
 // Use paint opacity for geometry visibility: filter changes reparse source tiles
 // and rapid hide/show can leave an older worker result on screen. Hit testing
 // independently checks the document so fully transparent areas stay unselectable.
 function apply(){const m=map.current;if(!m)return;host.current?.setAttribute('aria-busy','true');const d=latest.current.doc;for(const id of ['satellite','physical','streets'])m.setLayoutProperty('base-'+id,'visibility',d.basemap===id||(d.basemap==='rivers'&&id==='physical')?'visible':'none');applyOverlays(m,d);m.setLayoutProperty('kashmir-context-names','visibility',visible(areaById.get('kashmir-united')!,d)&&d.names?'visible':'none');m.setLayoutProperty('kashmir-context-names','text-size',d.labelSize+2);m.setPaintProperty('background','background-color',d.bg);for(const k of Object.keys(data.current)){const layerAreas=areasByLayer.get(k);if(!layerAreas)continue;const sample=layerAreas[0];const list=layerAreas.filter(a=>visible(a,d));const show=list.length>0;const ids=list.map(a=>a.id);const filter:FilterSpecification=['in',['get','id'],['literal',ids]];const line=sample.level==='region'||(sample.level==='province'?d.provinceBorders:sample.level==='district'?d.districtBorders:sample.level==='tehsil'?d.tehsilBorders:sample.level==='division'?d.divisionBorders:d.detailBorders);for(const suffix of ['fill','line','stripes','dots','cross','labels'])if(m.getLayer(k+'-'+suffix)){m.setLayoutProperty(k+'-'+suffix,'visibility',show&&(suffix!=='labels'||(d.names&&sample.region!=='kashmir-united'))?'visible':'none');if(suffix==='labels')m.setFilter(k+'-'+suffix,filter)}const painted=list.filter(a=>effectivePaint(a,d));const fillColor=list.length?['match',['get','id'],...list.flatMap(a=>[a.id,effectivePaint(a,d)?.color||d.uncolored]),d.uncolored] as unknown as ExpressionSpecification:d.uncolored;m.setPaintProperty(k+'-fill','fill-color',fillColor);const fillOpacity:number|ExpressionSpecification=sample.level==='division'?0:d.basemap==='political'?1:sample.level==='region'?0:['case',['in',['get','id'],['literal',painted.map(a=>a.id)]],d.opacity,0];m.setPaintProperty(k+'-fill','fill-opacity',['case',['in',['get','id'],['literal',ids]],fillOpacity,0]);m.setPaintProperty(k+'-line','line-opacity',['case',['in',['get','id'],['literal',ids]],d.borders&&line?1:0,0]);m.setPaintProperty(k+'-line','line-color',d.border);m.setPaintProperty(k+'-line','line-width',sample.level==='region'?d.width*1.8:sample.level==='province'?d.width*1.5:sample.level==='division'?d.width*2:sample.level==='tehsil'?d.width*.65:d.width);m.setLayoutProperty(k+'-labels','text-size',d.labelSize+(sample.level==='region'?2:sample.level==='uc'?-1:0));for(const pattern of ['stripes','dots','cross'])if(m.getLayer(k+'-'+pattern))m.setPaintProperty(k+'-'+pattern,'fill-opacity',['case',['in',['get','id'],['literal',list.filter(a=>effectivePaint(a,d)?.pattern===pattern).map(a=>a.id)]],fillOpacity,0]);}
 // Keep borders and labels above all fills after asynchronous layer loads.
 for(const level of levels)for(const k of Object.keys(data.current).filter(k=>k.endsWith('-'+level))){m.moveLayer(k+'-line');m.moveLayer(k+'-labels')}if(m.getLayer('kashmir-united-region-line'))m.moveLayer('kashmir-united-region-line');if(m.getLayer('delhi-ncr-region-line'))m.moveLayer('delhi-ncr-region-line');if(m.getLayer('tibet-modern-three-region-line'))m.moveLayer('tibet-modern-three-region-line');for(const id of ['river-lines','river-names','city-dots','city-names','gurdwara-symbols','kashmir-context-names'])m.moveLayer(id);applyMetro(m,d);m.triggerRepaint();
 }
 useEffect(()=>{if(!loaded||!map.current)return;const m=map.current;if(props.doc.delhiMetro)loadMetro(m);const masksNeeded=(props.doc.cities||props.doc.rivers||props.doc.basemap==='rivers'||props.doc.gurdwaras||props.doc.delhiMetro&&(props.doc.mapScope!=='atlas'||props.doc.delhiView==='ncr'||!!props.doc.countryView))?scopeGeometryKeys(props.doc):[];const wanted=[...new Set([...layerKeys.filter(k=>areasByLayer.get(k)!.some(a=>visible(a,{...props.doc,hidden:[]}))),...masksNeeded])];for(const kind of ['cities','rivers','gurdwaras'] as const)if(kind==='cities'?props.doc.cities:kind==='rivers'?props.doc.rivers||props.doc.basemap==='rivers':props.doc.gurdwaras)loadOverlay(m,kind);for(const k of wanted){if(data.current[k]||pending.current.has(k))continue;pending.current.add(k);latest.current.onStatus('Loading boundary detail…');Promise.all([fetch('/data/'+k+'.geojson').then(r=>{if(!r.ok)throw Error(k);return r.json()}),fetch('/data/'+k+'-labels.geojson').then(r=>{if(!r.ok)throw Error(k+' labels');return r.json()})]).then(([geo,labels])=>{if(!map.current)return;const a=areasByLayer.get(k)![0];m.addSource(k,{type:'geojson',data:geo as FeatureCollection,tolerance:.2,maxzoom:15});m.addSource(k+'-points',{type:'geojson',data:labels as FeatureCollection});const outline=a.level==='division';m.addLayer({id:k+'-fill',source:k,type:'fill',paint:{'fill-color':['coalesce',['feature-state','color'],latest.current.doc.uncolored] as ExpressionSpecification,'fill-opacity':outline?0:1}});for(const style of ['stripes','dots','cross'])m.addLayer({id:k+'-'+style,source:k,type:'fill',paint:{'fill-pattern':style,'fill-opacity':0}});m.addLayer({id:k+'-line',source:k,type:'line',paint:{'line-color':latest.current.doc.border,'line-width':1,...(a.level==='tehsil'?{'line-dasharray':[3,2]}:{})}});m.addLayer({id:k+'-labels',source:k+'-points',type:'symbol',minzoom:a.level==='uc'?10:a.level==='tehsil'?7.3:a.level==='district'?4.5:a.level==='province'?4.2:3,layout:{'text-field':['get','name'],'text-font':['Noto Sans Regular'],'text-size':12,'text-max-width':10,'text-padding':4,'text-allow-overlap':false},paint:{'text-color':'#1b354e','text-halo-color':'#ffffff','text-halo-width':1.5}});data.current[k]=geo as FeatureCollection;pending.current.delete(k);
 // Restore the hierarchy so tehsils and local detail receive clicks above districts.
 for(const level of ['region','province','district','tehsil','uc','division'])for(const key of Object.keys(data.current).filter(s=>s.endsWith('-'+level)))for(const suffix of ['fill','stripes','dots','cross'])m.moveLayer(key+'-'+suffix);apply();latest.current.onStatus('Boundary layer loaded')}).catch(()=>{pending.current.delete(k);latest.current.onStatus('Could not load '+k+'. Toggle the layer to retry.')})}apply();
 },[props.doc,loaded]);
 return <div className="gl-map"><div ref={host} className="gl-host"/>{error&&<div className="map-error">{error}</div>}{!loaded&&!error&&<div className="map-loading">Preparing map…</div>}{selection.length>0&&<svg className="selection-overlay"><g fill="#2764d82b" stroke="#2764d8" strokeDasharray="5 4" strokeWidth="2">{props.tool==='polygon'?<polygon points={selection.map(p=>p.join(',')).join(' ')}/>:selection.length>1&&props.tool==='ellipse'?<ellipse cx={(selection[0][0]+selection[1][0])/2} cy={(selection[0][1]+selection[1][1])/2} rx={Math.abs(selection[0][0]-selection[1][0])/2} ry={Math.abs(selection[0][1]-selection[1][1])/2}/>:selection.length>1?<rect x={Math.min(selection[0][0],selection[1][0])} y={Math.min(selection[0][1],selection[1][1])} width={Math.abs(selection[0][0]-selection[1][0])} height={Math.abs(selection[0][1]-selection[1][1])}/>:null}</g></svg>}</div>
}

