'use client';
import {Waves,Mountain,Trees,Layers2} from 'lucide-react';
import type {MapDoc} from './map-model';
import {scopeLabel} from './scope-model';
import {natureSources,riverSources} from './nature-model';
export default function NatureControls({doc,onChange}:{doc:MapDoc;onChange:(patch:Partial<MapDoc>)=>void}){
 return <section className="nature-controls" aria-label="Natural features">
  <div className="nature-intro"><span className="eyebrow">POLITICAL + PHYSICAL</span><p>Add physical features to any map. Layers follow your selected territories.</p><small>{scopeLabel(doc)}</small></div>
  <div className="nature-presets"><button onClick={()=>onChange({basemap:'political',rivers:true,mountains:true,plateaus:true,forests:true})}>Political + nature</button><button onClick={()=>onChange({rivers:true,riverDetail:'tributaries',mountains:false,plateaus:false,forests:false})}>River study</button><button onClick={()=>onChange({rivers:false,mountains:false,plateaus:false,forests:false,...(doc.basemap==='rivers'?{basemap:'political'}:{})})}>Clear nature</button></div>
  <div className="nature-layer"><label className="nature-layer-heading"><Waves size={21}/><span><strong>Rivers & tributaries</strong><small>From major rivers to regional networks</small></span><input type="checkbox" aria-label="Show rivers" checked={doc.rivers||doc.basemap==='rivers'} onChange={e=>onChange({rivers:e.target.checked,...(!e.target.checked&&doc.basemap==='rivers'?{basemap:'political'}:{})})}/></label>
   {(doc.rivers||doc.basemap==='rivers')&&<div className="nature-layer-options"><label className="field">River detail<select aria-label="River detail" value={doc.riverDetail} onChange={e=>onChange({riverDetail:e.target.value as MapDoc['riverDetail']})}><option value="major">Major named rivers · Natural Earth</option><option value="regional">Regional network · order 5+</option><option value="tributaries">More tributaries · order 3+</option></select></label><label className="overlay-color"><input type="color" aria-label="River color" value={doc.riverColor} onChange={e=>onChange({riverColor:e.target.value})}/> Line color</label><label className="field">Line width · {doc.riverWidth}px<input type="range" aria-label="River width" min={.5} max={6} step={.5} value={doc.riverWidth} onChange={e=>onChange({riverWidth:+e.target.value})}/></label><label className="overlay-toggle"><input type="checkbox" aria-label="Show river names" checked={doc.riverLabels} onChange={e=>onChange({riverLabels:e.target.checked})}/> Major river names</label><p className="muted">{riverSources.count.toLocaleString()} source reaches across the atlas. Names come from Natural Earth; tributaries are generally unnamed. Modelled at ~500 m; canals and small streams are incomplete.</p></div>}
  </div>
  {([{key:'mountains',color:'mountainColor',title:'Mountains & ranges',subtitle:'Named ranges and foothills',Icon:Mountain},{key:'plateaus',color:'plateauColor',title:'Plateaus',subtitle:'Broad plateau regions',Icon:Layers2},{key:'forests',color:'forestColor',title:'Forests / tree cover',subtitle:'ESA WorldCover · 2021 overview',Icon:Trees}] as const).map(({key,color,title,subtitle,Icon})=><div className="nature-layer" key={key}><label className="nature-layer-heading"><Icon size={21}/><span><strong>{title}</strong><small>{subtitle}</small></span><input type="checkbox" aria-label={'Show '+key} checked={doc[key]} onChange={e=>onChange({[key]:e.target.checked})}/></label>{doc[key]&&<div className="nature-layer-options"><label className="overlay-color"><input type="color" aria-label={title+' color'} value={doc[color]} onChange={e=>onChange({[color]:e.target.value})}/> Layer color</label><p className="muted">{key==='forests'?'Tree-cover overview at ~1.3 km pixels. Includes some plantations; small woods may be absent. This is not a current or 10 m forest inventory.':'Approximate Natural Earth physical regions. Shading shows broad landforms, not elevation contours or surveyed limits.'}</p></div>}</div>)}
  <label className="field">Shading opacity · {Math.round(doc.natureOpacity*100)}%<input type="range" aria-label="Nature shading opacity" min={.1} max={.85} step={.05} value={doc.natureOpacity} onChange={e=>onChange({natureOpacity:+e.target.value})}/></label>
  <label className="overlay-toggle"><input type="checkbox" aria-label="Show landform names" checked={doc.landformLabels} onChange={e=>onChange({landformLabels:e.target.checked})}/> Mountain & plateau names</label>
  <details className="nature-sources"><summary>Sources & coverage</summary><p><a href={riverSources.url} target="_blank" rel="noreferrer">RiverATLAS · CC BY 4.0</a></p><p><a href={natureSources.landforms.url} target="_blank" rel="noreferrer">Natural Earth · public domain</a></p><p><a href={natureSources.forest.url} target="_blank" rel="noreferrer">ESA WorldCover 2021 · CC BY 4.0</a></p><p className="muted">{natureSources.forest.credit}. Sources are bundled for offline use. If no source feature intersects a selection, that layer is empty.</p></details>
 </section>;
}
